### ISSUE TITLE
Bazarr or subtitle support

### ISSUE THREAD

**Issue by bycytov** [lardbit/nefarious#102]
New feature request. 
new user here. I’ve been enjoying using nefarious for a few weeks now. Works perfectly but is there anyway to auto scrape subtitles and include them in the download path after nefarious processes the download?

basically when the movie is done downloading and is renamed to the download location. Grab subtitles from the internet and place them next to the movie file so it can be picked up by plex. I’ve never used bazarr but it claims to do this with radar and sonarr

**Comment by lardbit** [comment]
Yeah I'm actually in the middle of adding that feature.

I'll update this issue when it's complete. It adds the option to automatically download subtitles from Open Subtitles.

https://github.com/lardbit/nefarious/tree/open-subtitles

**Comment by lardbit** [comment]
I just merged the Subtitles feature.  See https://github.com/lardbit/nefarious/pull/103

Let me know if you run into any issues or have feedback.

**Comment by bycytov** [comment]
Having trouble connecting my opensubtitles account. I’ve tried creating multiple new accounts. All I get is “unable to authenticate with provided credentials” knowing that these usernames and passwords are correct. Any suggestions?

**Comment by lardbit** [comment]
Hm, their api is new and had 2 different places to create accounts. Maybe I misunderstood. Let me test and get back to you.

**Comment by lardbit** [comment]
I think I may know your issue.  I created a new account on Open Subtitles and received an authentication error in nefarious when trying to configure it.  What I realized was that I had to confirm my email for Open Subtitles for my new account to be fully active.  Once I did that, it authenticated successfully within nefarious.

![image](https://user-images.githubusercontent.com/45122868/114408509-17ecc480-9b6f-11eb-9b24-14044923c6a7.png)

**Comment by lardbit** [comment]
@bycytov, I think I may know your issue. I created a new account on Open Subtitles and received an authentication error in nefarious when trying to configure it. What I realized was that I had to confirm my email for Open Subtitles for my new account to be fully active. Once I did that, it authenticated successfully within nefarious.

Let me know if that works for you.


![image](https://user-images.githubusercontent.com/45122868/114408687-48346300-9b6f-11eb-9f07-80da24f29b3f.png)

**Comment by bycytov** [comment]
Can confirm on my 3rd new account. Even after clicking on the link sent to my email nefarious won’t accept credentials. I know these credentials are legitimate as I can sign into opensubtitles in another tab. Is there another way you are confirming your email besides the email automatically sent to email when creating a new account?

**Comment by lardbit** [comment]
Ugh, I believe found the confusion.  Apparently their "new" system is on .com vs .org.  So register @ https://www.opensubtitles.com/en

**Comment by bycytov** [comment]
Worked right away. Sorry for the confusion thanks for the support. Love the project

**Comment by lardbit** [comment]
Glad we got it sorted out.  It was my fault, I put the .org domain in there.  I've updated it correctly now.  Thanks for helping test it.
