### ISSUE TITLE
Is there a way to disable ipv6?

### ISSUE THREAD

**Issue by DillFrescott** [lardbit/nefarious#114]
The VPS provider I use doesn't have ipv6 support. So when I try to install Nefarious; Jackett and Transmission fail to start up.

Is there a way to disable ipv6 entirely?

**Comment by lardbit** [comment]
nefarious uses the https://haugene.github.io/docker-transmission-openvpn/ package for VPN.  I can't speak for this ipv6 issue you're seeing, but a quick google led me to a few places that may be helpful:

https://github.com/haugene/docker-transmission-openvpn/issues/847#issuecomment-508707104
https://github.com/haugene/docker-transmission-openvpn/issues/516

good luck

**Comment by DillFrescott** [comment]
Ok. Thank you!
