### ISSUE TITLE
Add paging to search UI

### ISSUE THREAD

**Issue by panmau** [lardbit/nefarious#115]
When searching for movies only the first ~20 movies are shown. When your wished movie is not on that page, you can't add that movie. So I suggest to add paging like on themoviedb.
By the way: a filter like "release year" would be very nice to have.

Both of these features are supported by their API: https://developers.themoviedb.org/3/search/search-movies

**Comment by lardbit** [comment]
Good points! I guess I've never needed to page next on the search page. I like the release date filter as well. I'll keep this open until I have time to work on it.

**Comment by panmau** [comment]
I noticed this issue when I was trying to add the movie [Burning](https://www.themoviedb.org/movie/491584-burning).
Is there a way to manually circumvent this limitation for the time being?

**Comment by lardbit** [comment]
Yeah, a workaround is to just swap the tmdb id in the URL.  So, just click on a random search result, and then swap the id in the URL.  So, *Burning* has the tmdb id of **491584** so swap like:

- http://nefarious.example.com/static/index.html#/media/movie/123456
- http://nefarious.example.com/static/index.html#/media/movie/491584

![image](https://user-images.githubusercontent.com/45122868/118015247-ae043e00-b319-11eb-9f85-df2264c731cf.png)

**Comment by lardbit** [comment]
^ I got the tmdb id of *Burning* from the link you provided.  It's in the URL.

**Comment by lardbit** [comment]
@panmau, I added paging to the *Search* screen.  See f5d86eabf5401d99f6418a280ba9d8e194c48bf0.  I'm closing this ticket but keep in mind it'll take an hour or so for the docker image to be built via Github Actions.
