### ISSUE TITLE
psycopg2 dependency missing to be able to use Postgres

### ISSUE THREAD

**Issue by stenwt** [lardbit/nefarious#126]
I tried using Postgres with Nefarious, which fails like: 

```django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named 'psycopg2'
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 25, in <module>
    import psycopg2 as Database
ModuleNotFoundError: No module named 'psycopg2'
```

Fixing this is trivial, but I wanted to call one thing out: there are two options, one is to build psycopg2 from source in the Docker build, the other is to install psycopg2-binary from PyPi. The latter doesn't appear to be available for arm v7, and I see you're currently publishing images for x86_64, aarch64, armv7, so I think that crosses out the binary build, but if you ever drop support for armv7, or psycopg2-binary ever gets published for armv7, using psycopg2-binary may save some build time.

**Comment by stenwt** [comment]
#127

**Comment by lardbit** [comment]
Thanks for the contribution!  Building for arm keeps throwing wrenches in my builds (I run this on a raspberry pi 2).   I had a similar issue from an npm / sass library where it had to be built from source and it took about 45 minutes.  Luckily a binary was eventually provided.  This seems like an identical problem.  I followed the https://github.com/psycopg/psycopg2/issues/1125 thread and it seems like they're close on an arm wheel.  I'm trying to find out how long the builds are going to be now that it's building from source, but your PR is still processing so I'll check back later.  I think it's fine even if it takes a while.  I think GitHub Actions permits long running workflows.

**Comment by lardbit** [comment]
I merged your PR into master.  You probably already figured it out, but to use postgres just update `docker-compose.base.yml` and change the environment variable `DATABASE_URL` to something like:

      postgres://USER:PASSWORD@HOST:PORT/NAME

The various db formats are documented in the library I'm using: https://github.com/kennethreitz/dj-database-url#url-schema

*Note to self: It makes more sense to move the `DATABASE_URL` variable into the `.env` file so you don't have to ever modify the docker compose files.*
