### ISSUE TITLE
ERROR: Version in "./docker-compose.yml" is unsupported

### ISSUE THREAD

**Issue by isAAAc** [lardbit/nefarious#130]
Hello, 
on a fresh install, i can't launch the app:
```bash
~/git/nefarious$ git pull -r
Already up to date.


~/git/nefarious$ docker-compose up -d
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```
thx for your help

**Comment by isAAAc** [comment]
dirty fix: 
setting 2.2 version in `docker-compose.base.yml` and `docker-compose.yml`
but why 2.4 doesn't work ?

**Comment by lardbit** [comment]
I'm guessing your **docker-compose** binary doesn't support the *docker compose* **2.4** `version`.

What version of docker-compose do you have?  Run

    docker-compose -v

See https://docs.docker.com/compose/compose-file/compose-file-v2/ for the version matrix to know what it expects.  

Long story short, just try updating your `docker-compose` binary.

**Comment by lardbit** [comment]
Closed due to inactivity.
