### ISSUE TITLE
Titles with path delimiters break processing

### ISSUE THREAD

**Issue by KovuTheHusky** [lardbit/nefarious#134]
After a download is completed, Nefarious will attempt to rename the file with the title. If it includes a path delimiter (forward slash) it will fail and prevent any completed downloads from being processed, bringing everything to a halt until that is removed from Nefarious.

Unfortunately I had the log for this but I cannot locate it. I believe this issue is fairly easy to diagnose and fix though. I will attempt to snag a log if needed. Please let me know, thanks!

**Comment by lardbit** [comment]
Ah, yeah you're right.  I noticed the media software I use, Plex, chokes on colons, so I swapped them out during the rename process.  I'll do the same for path delimiters.  Any other characters I should consider cleaning?

**Comment by KovuTheHusky** [comment]
I'm not familiar with Plex's limitations despite using it for many years now. As far as linux/unix goes only forward-slash is not permitted. Windows is a nightmare and blocks a [bunch](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions) but I'm not sure if that matters.

**Comment by lardbit** [comment]
The python framework I use, Django, actually has a function to sanitize file names so I'll probably just use it:
[get_valid_filename](https://docs.djangoproject.com/en/3.0/_modules/django/utils/text/)

```python
def get_valid_filename(s):
    """
    Return the given string converted to a string that can be used for a clean
    filename. Remove leading and trailing spaces; convert other spaces to
    underscores; and remove anything that is not an alphanumeric, dash,
    underscore, or dot.
    >>> get_valid_filename("john's portrait in 2004.jpg")
    'johns_portrait_in_2004.jpg'
    """
    s = str(s).strip().replace(' ', '_')
    return re.sub(r'(?u)[^-\w.]', '', s)
```

You see any immediate problems with this?

**Comment by KovuTheHusky** [comment]
If it's just for the file name in the directory I see no issue. For the directory itself, I'd assume you still want to match Plex's standard (e.g. "The Matrix (1999)") format for auto-matching purposes. In that case I'd probably run just the title through the method and then concatenate it with the rest. You would certainly know more than I would though!

**Comment by lardbit** [comment]
Yeah, I agree.  I'll use the renaming function for file names and directories but will append the year and also maintain spaces (vs underscores).

**Comment by lardbit** [comment]
Updated! Thanks for helping brainstorm this. Please let me know if this resolves your issue. See #136 for details.
