### ISSUE TITLE
Fix - Manual search

### ISSUE THREAD

**Issue by RicardoVelaC** [lardbit/nefarious#14]
After you update manual search function, it doesn't work anymore in a language other than English. If I search one movie with the Spanish Title, works ok, movie found, but when I use the manual search, Nefarious use the English name to search in Jackett and it return only English results. My Jackett providers are local (Spanish) and found no results or different movies.

Can you use the local Title of IMDB or TMDB, or maybe the input search for make it work again?

Thanks!!

**Comment by lardbit** [comment]
Good point.  I'll work on updating the manual search feature to search against the original TMDB title vs the english title.

**Comment by lardbit** [comment]
@RicardoVelaC good catch.  I updated the manual searching feature to support whatever title/language you want.  It's merged into master. (#17 ).

**Comment by RicardoVelaC** [comment]
Thanks I tried it and now work for spanish search, you need to copy/paste the title but it's work

**Comment by lardbit** [comment]
TMDB supports internationalization which is where all the metadata comes from. I will look into this and see if I can make nefarious support it as well. 

https://developers.themoviedb.org/3/configuration/get-languages

I'm thinking I'll  let the user globally define their language in the main settings and then all queries to TMDB will match.

**Comment by RicardoVelaC** [comment]
It'll be a great point. I'm stay tuned

**Comment by lardbit** [comment]
I created a PR for internationalization.

https://github.com/lardbit/nefarious/pull/18

It tests ok for me, but I'll wait a few days to merge it in case you wanted to test drive it first.

The docker image is `lardbit/nefarious:i18n`

**Comment by lardbit** [comment]
#18 is merged to support internationalization.  You can now specify which language to use and all TMDB metadata will be localized.
