### ISSUE TITLE
Only display items which are available for download

### ISSUE THREAD

**Issue by dimqua** [lardbit/nefarious#15]
Is it possible to filter out movies and tv shows if they don't have any download sources?

**Comment by lardbit** [comment]
Are you asking to filter out movies/tv from the *Search* & *Discover* page results if there's no download results?

That, unfortunately, isn't really possible because you have to actually search the back-end (torrent indexing sites) before you can know if there's results or not.

**Comment by lardbit** [comment]
However, when you choose to "Watch" something that's not yet available for download, nefarious queues it up and will search for it everyday until it's available.
