### ISSUE TITLE
Struggling to find files

### ISSUE THREAD

**Issue by Clickbaitcake** [lardbit/nefarious#157]
Hello,

I assume I am doing something wrong but can't put my finger on it.
Transmission says downloads have completed and are in a folder `/downloads/movies/` but when I SSH to my server I can't see anything in that folder. 

Are my files inside the docker container filesystem instead of my actual host file system?

I have configured the path in `transmission-settings.json` and my `custom.env` file.

What am I doing wrong here?

**Comment by lardbit** [comment]
Yeah, nefarious (actually transmission) downloads things into a docker container file system, which should be mounted to your hosts' path as whatever you defined as `HOST_DOWNLOAD_PATH`.

You shouldn't be editing `transmission-settings.json` for most use cases.  Follow the [Setup](https://github.com/lardbit/nefarious#setup) and you'll see you just need an `.env` file which nefarious uses for it's initial configuration.

**Comment by Clickbaitcake** [comment]
It seems changing the download path in the `transmission-settings.json` file seemed to cause my issue. Totally self inflicted. Sorry for the pointless issue!
