### ISSUE TITLE
Feature Request: Torrent Size Limit

### ISSUE THREAD

**Issue by Clickbaitcake** [lardbit/nefarious#161]
Sometimes when requesting a movie in 1080p Nefarious will pick a file thats anywhere between 30-60GB. Some users might not have the disk space or have a powerful enough server to encode such a large file for playback. It would be nice to add a max file size to the selection logic. I think Sonarr and Radarr have this feature.

There could be an additional drop down near the quality selection which sets a GB limit on how large a torrent is.

**Comment by lardbit** [comment]
I like this idea.  nefarious should offer more fine-grained control over the quality profiles (size, encoding, anything else?).  I'll keep this open until I have time to tackle it.

**Comment by dfourn** [comment]
Slightly off-topic but it touches this area. Can we add a profile which would download the highest quality possible? Like, it would try to get 4k first, and if that's not available it'd try the 1080p and so on.

**Comment by lardbit** [comment]
@dfourn I like this idea.  nefarious currently chooses a result with the most seeds *within* the user's quality profile, but maybe we could add an option to the quality profile which will choose/force the highest quality (vs seeds) within their quality profile.
