### ISSUE TITLE
[Bug] Season mistakenly shown as watching & downloaded

### ISSUE THREAD

**Issue by panmau** [lardbit/nefarious#165]
In the UI of nefarious I found a TV series where the latest season is shown as being watched with all episodes downloaded. I'm not watching the season though, which I confirmed via the admin UI.

On a closer look I saw that there are currently no episodes assigned to it. This seems to me like it could be the reason for this a bit confusing visual bug:
![image](https://user-images.githubusercontent.com/16801528/147854546-4588744a-f606-4ae0-bfd8-7934bdefa2c0.png)

You should be able to confirm this behaviour via the following link: `/static/index.html#/media/tv/75816`

**Comment by lardbit** [comment]
You're right, mine does the same thing.  I noticed there aren't any episodes (via TDMB) for this season, which would help explain the GUI bug (my logic must have not accounted for this).  Thanks for reporting, it should be an easy fix.

![image](https://user-images.githubusercontent.com/45122868/147855296-385664bd-30fc-40a5-bb39-25d328b46052.png)

**Comment by lardbit** [comment]
Fixed by #166.
