### ISSUE TITLE
Unassigned released date results in error when watching a movie

### ISSUE THREAD

**Issue by panmau** [lardbit/nefarious#170]
When trying to watch the movie with id `466420` I get the error `An unknown error occured`. 

There's no release date assigned to it yet in TMDB. Therefore an empty string is sent to the server as the date.
This results in this 400 response: `{"release_date":["Date has wrong format. Use one of these formats instead: YYYY-MM-DD."]}`

**Comment by lardbit** [comment]
Thanks for reporting this bug with the helpful details.  #171 resolves it by passing null values vs empty strings when date is absent.

**Comment by panmau** [comment]
Thanks for the fix: Nefarious is getting better and better :)
