### ISSUE TITLE
Create full folder hierarchy for TV shows

### ISSUE THREAD

**Issue by Nautigsam** [lardbit/nefarious#19]
I tried to download a single episode of a TV show and Transmission downloaded it directly inside `/tv` folder. This causes some problems with my media center (jellyfin) because it expects to have some folder hierarchy like `Series > Season > Episode`.

Do you think it is possible to create such folders? The problem is some torrents contain the file directly, others have a folder at the root. I don't have too much experience with nefarious/transmission so I don't really know what is possible.

**Comment by lardbit** [comment]
Yes that makes sense.  I'll try and address this. Good catch.

**Comment by lardbit** [comment]
I believe to accomplish this I'd need to use a different torrent client than **Transmission** because it only supports renaming either the top level file or folder, but not **adding** a parent folder for a single file torrent.  Does that make sense?

From what I've been reading, **rtorrent** seems like a powerful alternative that includes some nice 3rd party GUI frontends.  Any other suggestions?  

That would be a fair amount of work but I'm not ruling it out.

Nefarious doesn't currently expect to have file system access to the downloads, so it's at the mercy of the ability of the transmission client to support such access.  I suppose that expectation could change if necessary.

**Comment by Ahuri3** [comment]
Are you sure about this ?

I haven't used the api but the webinterface of transmission allowed me to create folder hierarchies.
Like this : 
![image](https://user-images.githubusercontent.com/4500365/68551479-a35ba680-040d-11ea-941e-2e4c1d2ec85a.png)

Once the sample torrent downloaded it put the file in the right place.

**Comment by lardbit** [comment]
Hmm, if that works then you're probably right. Let me verify and I'll get back with you.

**Comment by Nautigsam** [comment]
I suppose Nefarious already tells Transmission where to save the file using what you set in the settings. I was thinking it would be possible to override this path for a given TV show.

**Comment by lardbit** [comment]
You're totally right. I don't know why I thought Transmission couldn't do it. nefarious was already using that feature.

This should do the trick:
https://github.com/lardbit/nefarious/commit/202162d77c617ff3b71a38318068ab94758c7911

However, it's not doing any intelligent Season + Episode grouping like *Show->Season>Episode*.  That's something I plan on eventually doing, though.

This quick update now includes a parent directory if the torrent is a single file.  

For instance, if you download a single episode like `Show S01E01.mkv` it will simply download it into `/path/to/tv/Show S01E01/Show S01E01.mkv`.

**Comment by lardbit** [comment]
Plex supports this *lazy* folder structure but I don't know if **jellyfish** does.  Let me know if not.

**Comment by Nautigsam** [comment]
Thanks for your work!
Here is the documentation for jellyfin for reference: https://jellyfin.org/docs/general/server/media/shows.html

Wouldn't it be more flexible to allow the user to choose where to save the file in Nefarious? It could default to the name of the show and the season since it is known. I can look into it once I get some time.

**Comment by lardbit** [comment]
Yeah you're right. That would definitely be better. I'll keep this issue open until I get a chance to address it.

**Comment by lardbit** [comment]
@Nautigsam I created a PR #27 .  I wrote some unit tests that are passing but I need to do some more manual testing as well.  It structures TV for you, as described in jellyfin.  It would be nice to let the user decide on the structure, but this is a good first start.

**Comment by lardbit** [comment]
Merged PR #27 into master.  Closing this issue as it should now be resolved.

**Comment by Nautigsam** [comment]
@lardbit That's great! Thank you for taking the time to fix this. I will try it asap.

**Comment by lardbit** [comment]
Great, glad it worked. Thanks for the suggestion.

**Comment by lardbit** [comment]
I finally figured out how to rename individual files, which will resolve some issues where files and folders get nested too deep in some situations.
