### ISSUE TITLE
Issue with Transmission - Couldn't read "/config/settings.json": Permission denied

### ISSUE THREAD

**Issue by xlr8ed2020** [lardbit/nefarious#197]
Hi,

I've just set this up on Photon OS running on an ESX server, everything is running as shown below:
root@srv-docker [ ~/nefarious ]# docker container ls
CONTAINER ID   IMAGE                      COMMAND                  CREATED             STATUS          PORTS                                                                                                 NAMES
316191cb2bbc   linuxserver/transmission   "/init"                  About an hour ago   Up 26 minutes   0.0.0.0:9091->9091/tcp, :::9091->9091/tcp, 0.0.0.0:51413->51413/tcp, :::51413->51413/tcp, 51413/udp   nefarious-transmission-1
8179c0037b74   lardbit/nefarious          "/app/entrypoint.sh"     5 hours ago         Up 3 hours      0.0.0.0:8000->80/tcp, :::8000->80/tcp                                                                 nefarious-nefarious-1
7fca678e6e16   lardbit/nefarious          "/app/entrypoint-cel…"   5 hours ago         Up 3 hours      80/tcp                                                                                                nefarious-celery-1
7261dc490f47   linuxserver/jackett        "/init"                  5 hours ago         Up 3 hours      0.0.0.0:9117->9117/tcp, :::9117->9117/tcp                                                             nefarious-jackett-1
88e3b1da32f3   containrrr/watchtower      "/watchtower --label…"   5 hours ago         Up 3 hours      8080/tcp                                                                                              nefarious-watchtower-1
1642eb20ae81   redis                      "docker-entrypoint.s…"   5 hours ago         Up 3 hours      6379/tcp                                                                                              nefarious-redis-1

However, the web interface for Transmission is not running and I'm getting the below error continuously:
root@srv-docker [ ~/nefarious ]# docker-compose logs -f transmission
nefarious-transmission-1  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
nefarious-transmission-1  | [s6-init] ensuring user provided files have correct perms...exited 0.
nefarious-transmission-1  | [fix-attrs.d] applying ownership & permissions fixes...
nefarious-transmission-1  | [fix-attrs.d] done.
nefarious-transmission-1  | [cont-init.d] executing container initialization scripts...
nefarious-transmission-1  | [cont-init.d] 01-envfile: executing...
nefarious-transmission-1  | [cont-init.d] 01-envfile: exited 0.
nefarious-transmission-1  | [cont-init.d] 01-migrations: executing...
nefarious-transmission-1  | [migrations] started
nefarious-transmission-1  | [migrations] no migrations found
nefarious-transmission-1  | [cont-init.d] 01-migrations: exited 0.
nefarious-transmission-1  | [cont-init.d] 02-tamper-check: executing...
nefarious-transmission-1  | [cont-init.d] 02-tamper-check: exited 0.
nefarious-transmission-1  | [cont-init.d] 10-adduser: executing...
nefarious-transmission-1  |
nefarious-transmission-1  | -------------------------------------
nefarious-transmission-1  |           _         ()
nefarious-transmission-1  |          | |  ___   _    __
nefarious-transmission-1  |          | | / __| | |  /  \
nefarious-transmission-1  |          | | \__ \ | | | () |
nefarious-transmission-1  |          |_| |___/ |_|  \__/
nefarious-transmission-1  |
nefarious-transmission-1  |
nefarious-transmission-1  | Brought to you by linuxserver.io
nefarious-transmission-1  | -------------------------------------
nefarious-transmission-1  |
nefarious-transmission-1  | To support LSIO projects visit:
nefarious-transmission-1  | https://www.linuxserver.io/donate/
nefarious-transmission-1  | -------------------------------------
nefarious-transmission-1  | GID/UID
nefarious-transmission-1  | -------------------------------------
nefarious-transmission-1  |
nefarious-transmission-1  | User uid:    1000
nefarious-transmission-1  | User gid:    1000
nefarious-transmission-1  | -------------------------------------
nefarious-transmission-1  |
nefarious-transmission-1  | [cont-init.d] 10-adduser: exited 0.
nefarious-transmission-1  | [cont-init.d] 20-config: executing...
nefarious-transmission-1  | sed: can't move '/config/settings.jsonEcdMMk' to '/config/settings.json': Resource busy
nefarious-transmission-1  | sed: can't move '/config/settings.jsonBMJAjh' to '/config/settings.json': Resource busy
nefarious-transmission-1  | sed: can't move '/config/settings.jsonikIOEm' to '/config/settings.json': Resource busy
nefarious-transmission-1  | sed: can't move '/config/settings.jsonmaeJbf' to '/config/settings.json': Resource busy
nefarious-transmission-1  | sed: can't move '/config/settings.jsonffhOGn' to '/config/settings.json': Resource busy
nefarious-transmission-1  | sed: can't move '/config/settings.jsonpJHLfb' to '/config/settings.json': Resource busy
nefarious-transmission-1  | sed: can't move '/config/settings.jsonAojBHH' to '/config/settings.json': Resource busy
nefarious-transmission-1  | chown: changing ownership of '/config/settings.json': Read-only file system
nefarious-transmission-1  | [cont-init.d] 20-config: exited 1.
nefarious-transmission-1  | [cont-init.d] 90-custom-folders: executing...
nefarious-transmission-1  | [cont-init.d] 90-custom-folders: exited 0.
nefarious-transmission-1  | [cont-init.d] 99-custom-files: executing...
nefarious-transmission-1  | [custom-init] no custom files found exiting...
nefarious-transmission-1  | [cont-init.d] 99-custom-files: exited 0.
nefarious-transmission-1  | [cont-init.d] done.
nefarious-transmission-1  | [services.d] starting services
nefarious-transmission-1  | [services.d] done.
nefarious-transmission-1  | [2022-06-20 06:16:06.926] Couldn't read "/config/settings.json": Permission denied
nefarious-transmission-1  | [2022-06-20 06:16:06.926] transmission-daemon Error loading config file -- exiting. (/home/buildozer/aports/community/transmission/src/transmission-3.00/daemon/daemon.c:825)
nefarious-transmission-1  | [2022-06-20 06:16:07.757] Couldn't read "/config/settings.json": Permission denied
nefarious-transmission-1  | [2022-06-20 06:16:07.757] transmission-daemon Error loading config file -- exiting. (/home/buildozer/aports/community/transmission/src/transmission-3.00/daemon/daemon.c:825)
nefarious-transmission-1  | [2022-06-20 06:16:08.761] Couldn't read "/config/settings.json": Permission denied
nefarious-transmission-1  | [2022-06-20 06:16:08.761] transmission-daemon Error loading config file -- exiting. (/home/buildozer/aports/community/transmission/src/transmission-3.00/daemon/daemon.c:825)
nefarious-transmission-1  | [2022-06-20 06:16:09.762] Couldn't read "/config/settings.json": Permission denied
nefarious-transmission-1  | [2022-06-20 06:16:09.762] transmission-daemon Error loading config file -- exiting. (/home/buildozer/aports/community/transmission/src/transmission-3.00/daemon/daemon.c:825)
nefarious-transmission-1  | [2022-06-20 06:16:10.764] Couldn't read "/config/settings.json": Permission denied
nefarious-transmission-1  | [2022-06-20 06:16:10.764] transmission-daemon Error loading config file -- exiting. (/home/buildozer/aports/community/transmission/src/transmission-3.00/daemon/daemon.c:825)
nefarious-transmission-1  | [2022-06-20 06:16:11.765] Couldn't read "/config/settings.json": Permission denied
nefarious-transmission-1  | [2022-06-20 06:16:11.765] transmission-daemon Error loading config file -- exiting. (/home/buildozer/aports/community/transmission/src/transmission-3.00/daemon/daemon.c:825)
nefarious-transmission-1  | [2022-06-20 06:16:12.768] Couldn't read "/config/settings.json": Permission denied
nefarious-transmission-1  | [2022-06-20 06:16:12.769] transmission-daemon Error loading config file -- exiting. (/home/buildozer/aports/community/transmission/src/transmission-3.00/daemon/daemon.c:825)

Can anyone please help?

**Comment by lardbit** [comment]
Offhand it looks like a permissions issue, but I can't identify why.  I see you're running this container as `root`.  Transmission gets run as a different user, so I'm wondering if your host permissions for `transmission-settings.json` aren't loose enough for the mounted volume?

**Comment by lardbit** [comment]
Closed due to inactivity.
