### ISSUE TITLE
Remove auth requirement

### ISSUE THREAD

**Issue by flic** [lardbit/nefarious#206]
Great project!

I'm currently using an auth forwarder in my reverse proxy in front of my published web apps, so the basic auth login in Nefarious is a bit of a nuisance actually. Is there a way to disable the authentication?

**Comment by lardbit** [comment]
No, sorry, there's no current way to disable it.  But once you're logged in the session doesn't expire so it should only be a *nuisance* once.

**Comment by flic** [comment]
Good enough, thanks!
