### ISSUE TITLE
Possibility to select "5.1" as a quality option

### ISSUE THREAD

**Issue by panmona** [lardbit/nefarious#211]
I frequently find myself manually searching for torrents via nefarious and using the search term "5.1" to find torrents with 5.1 audio quality, as the automatic searching doesn't always select a 5.1 torrent.

Would it be possible to add an audio quality filter option?

**Comment by lardbit** [comment]
Yeah, good point. I'm going to add this in #212, to be able to choose a quality profile, e.g **1080p** with other attributes like **5.1**, **HDR** etc.

**Comment by lardbit** [comment]
You can now apply "5.1" rules to quality profiles.  See https://github.com/lardbit/nefarious/pull/212
