### ISSUE TITLE
[Feature] Able to specify own folder structure

### ISSUE THREAD

**Issue by Zelaf** [lardbit/nefarious#216]
I use a NFS share to my NAS on my Pi to use Nefarious and would be nice if I was able to integrate Nefarious to my already existing folder structure. Since I have my movies on a folder called "Movies" it created a new folder called "movies" instead. Same with "TV Shows" being just "tv". I would love to have a bit better folder structure when browsing my DLNA shares over my network through my Xbox and such so that it looks a bit better on those devices! As well as having a separate "Downloads" folder as to not clutter my main Media folder!

**Comment by lardbit** [comment]
The **sub-folders** are configurable.  They default to `movies` and `tv` but can be changed in the main settings page.

![image](https://user-images.githubusercontent.com/45122868/189732312-cd4f526e-ec5a-4108-8ec2-5c5da83566d7.png)

**Comment by lardbit** [comment]
Closed due to inactivity.
