### ISSUE TITLE
Connection to Jackett fails with "No address associated with hostname"

### ISSUE THREAD

**Issue by panmau** [lardbit/nefarious#218]
I set up Nefarious on a new computer and I use the .env I had on my old computer.

I copied the API token from Jackett and put into the corresponding input field but for some reason I get the following errors when trying to Save & Verify the settings:

```
nefarious-nefarious-1  | INFO:     172.19.0.1:55488 - "PATCH /api/settings/1/ HTTP/1.1" 200 OK
nefarious-nefarious-1  | ERROR  2022-09-09 09:17:02,789  utils 56  140598700914432  HTTPConnectionPool(host='jackett', port=9117): Max retries exceeded with url: /api/v2.0/indexers/all/results?apikey={redactd} (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdfaea8d1f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
nefarious-nefarious-1  | ERROR:nefarious-foreground:HTTPConnectionPool(host='jackett', port=9117): Max retries exceeded with url: /api/v2.0/indexers/all/results?apikey={redacted} (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdfaea8d1f0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
nefarious-nefarious-1  | WARNING:django.request:Bad Request: /api/settings/1/verify-jackett-indexers/
nefarious-nefarious-1  | INFO:     172.19.0.1:55488 - "GET /api/settings/1/verify-jackett-indexers/ HTTP/1.1" 400 Bad Request
```

Of course that also means that no download requests are working.

Jackett is normally available via http://localhost:9117/UI/Dashboard and I didn't change any other settings.

Is there anything I'm missing here?

**Comment by lardbit** [comment]
Is the new setup using VPN?  If so, you'll need to use `transmission` (vs `jackett`) as the **host** in the settings.   See https://github.com/lardbit/nefarious/blob/master/docs/VPN.md

**Comment by panmau** [comment]
Ah, yes that was it! 
I somehow missed this while re-reading all documentation for it.

Thank you!
