### ISSUE TITLE
[Feature] Prowlarr Support

### ISSUE THREAD

**Issue by bycytov** [lardbit/nefarious#220]
Would be nice to use instead of Jackett. My experience this is much better

**Comment by lardbit** [comment]
wow, I had no idea there was a popular competitor to jackett, and it supports usenet.  I'll have to test drive this at some point to fully understand it.  Thanks for sharing.

**Comment by lardbit** [comment]
I'm closing this because I don't plan on extending support beyond jackett unless jackett closes it's doors.
