### ISSUE TITLE
[Feature] Language / Region Filter for TV Discovery

### ISSUE THREAD

**Issue by zer0TF** [lardbit/nefarious#235]
Under "Discover" > The Move Database > Type: TV and Sort: Popular, currently this list produces worldwide content.

It would be nice if we could filter this list to only TV from a certain region or language.

If The Movie Database doesn't do this, perhaps we could implement **The TV DB** instead, which has tags for *Original Language* and *Originating Country*? (https://thetvdb.com/)

**Comment by lardbit** [comment]
yeah, that's not a bad idea and that data is indeed included in TMDB.  I'll
keep this ticket open until I get time to work on it.  Contributions are
always welcome too.

**Comment by lardbit** [comment]
Well, shoot.  I started to develop this then realized TMDB only uses the "region" specifier for presentation (display results for that region/language).

https://developer.themoviedb.org/docs/region-support
