### ISSUE TITLE
server completely un responding after 10-15 hours of running 

### ISSUE THREAD

**Issue by toxinliquid** [lardbit/nefarious#238]
server : ubuntu 20.04
environment : VMware with 4 cores and 16 GB ram 

scenario:
after booting nefarious virtual machine , the server will preform as intended , but after 10-15 hours it will completely freeze and the webpage is unresponsive , freezing all other virtual machines along with it.

steps tried to resolve the issue:
turned of all other virtual machines , the issue still happens.

**Comment by lardbit** [comment]
This sounds like a host/vm issue because nefarious wouldn't have the ability to affect other virtual machines.  That's the whole point of vm's, is that they're completely separated.  

Try just running nefarious on your host via docker-compose and see how that goes.
