### ISSUE TITLE
cant change download location from tmp

### ISSUE THREAD

**Issue by toxinliquid** [lardbit/nefarious#244]
i edited xxx.env  docker-compose.yml  and docker-compose.base.yml but nothing worked

any idea how to change it ?

**Comment by toxinliquid** [comment]
edit env.template 
then
cp env.template .env

**Comment by lardbit** [comment]
You shouldn't be editing any of the docker-compose*.yml files.  Instead, all edits should be in the `.env` file.  

Then restart everything with:

    docker-compose up -d --force-recreate
