### ISSUE TITLE
Transmission permission error

### ISSUE THREAD

**Issue by ShrekRequiem** [lardbit/nefarious#245]
I get this error that doesnt let me connect to transmission, ive tried running it as privileged, manually creating the files but nothing works.

```GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
usermod: Failed to change ownership of the home directorycp: cannot stat '/config/settings.json': Permission denied
sed: /config/settings.json: Permission denied
sed: /config/settings.json: Permission denied
sed: /config/settings.json: Permission denied
sed: /config/settings.json: Permission denied
sed: /config/settings.json: Permission denied
sed: /config/settings.json: Permission denied
sed: /config/settings.json: Permission denied
chown: cannot access '/config/settings.json': Permission denied
**** Permissions could not be set. This is probably because your volume mounts are remote or read-only. ****
**** The app may not work properly and we will not provide support for it. ****
[custom-init] No custom files found, skipping...
[2023-03-16 21:45:55.868] utils.cc:76: Couldn't read '/config/settings.json': Permission denied (13)
[2023-03-16 21:45:55.868] ERR transmission-daemon Error loading config file -- exiting. (/home/buildozer/aports/community/transmission/src/transmission-4.0.2/daemon/daemon.cc:914)
tail: invalid PID: ‘’
```

**Comment by lardbit** [comment]
It certainly sounds like a permissions issue.  Are you doing anything custom during the installation process or following the steps verbatim?

Try this: bring everything down, change file permissions, then bring everything back up.

Bring down:

    docker-compose down -v

Make sure transmission settings are globally readable:

    chmod a+r transmission-settings.json

Bring back up:

    docker-compose up -d

**Comment by lardbit** [comment]
Ok you're getting so close!  

So it looks like nefarious isn't able to connect to transmission... can you run the following commands and let me know what they say?

First let's make sure transmission is running correctly (let me know what it says):

    docker-compose ps

Then, click the *Save & verify settings* button again on the settings page, then run the following and see what the logs says:

    docker-compose logs transmission

Lastly, does http://localhost:9091/transmission/web/ load for you without the need for a user/pass?

**Comment by ShrekRequiem** [comment]
docker-compose ps returns

```
          Name                        Command                 State                        Ports
------------------------------------------------------------------------------------------------------------------
nefarious_celery_1         /app/entrypoint-celery.sh        Up           80/tcp
nefarious_jackett_1        /init                            Up           0.0.0.0:9117->9117/tcp,:::9117->9117/tcp
nefarious_nefarious_1      /app/entrypoint.sh               Up           0.0.0.0:8008->80/tcp,:::8008->80/tcp
nefarious_redis_1          docker-entrypoint.sh redis ...   Up           6379/tcp
nefarious_transmission_1   /init                            Up           0.0.0.0:51413->51413/tcp,:::51413-
                                                                         >51413/tcp, 51413/udp,
                                                                         0.0.0.0:9091->9091/tcp,:::9091->9091/tcp
nefarious_watchtower_1     /watchtower --label-enable ...   Restarting
```

and docker-compose logs transmission returns this in a loop

```
transmission_1  | [2023-03-17 18:11:35.466] utils.cc:76: Couldn't read '/config/settings.json': Permission denied (13)
transmission_1  | [2023-03-17 18:11:35.466] ERR transmission-daemon Error loading config file -- exiting. (/home/buildozer/aports/community/transmission/src/transmission-4.0.2/daemon/daemon.cc:914)
transmission_1  | tail: invalid PID: ‘’
```

**Comment by lardbit** [comment]
Transmission is still complaining it can't access the settings.json file, which is actually the `transmission-settings.json` file on your host that gets mounted inside transmission.  I can't figure out what would cause it to not be able to access it...

Let's see what the permissions are inside the transmission container.  Run this and let me know:

    docker-compose exec transmission ls -al /config/settings.json

It should look something like this:

    -rw-rw-r-- 1 abc users 193 Mar 17 17:54 /config/settings.json

Then try and have transmission read it's own settings file:

    docker-compose exec transmission cat /config/settings.json

Which should look something like:

    {
    "download-dir": "/downloads/",
    "incomplete-dir": "/downloads/.incomplete",
    "incomplete-dir-enabled": "true",
    "rpc-whitelist": "*",
    "rpc-host-whitelist-enabled": "false"
    }

**Comment by ShrekRequiem** [comment]
The commands returns

`ls: cannot access '/config/settings.json': Permission denied`
`cat: /config/settings.json: Permission denied`

even when I run with sudo

if that helps there is no config file in the directory but I just assumed it was supposed to be built during the installation or something

**Comment by lardbit** [comment]
Ok let's see if transmission can read **any** of it's own files:

    docker-compose exec transmission ls -al /

**Comment by ShrekRequiem** [comment]
```
total 32
drwxr-xr-x   1 root root    420 Mar 17 15:36 .
drwxr-xr-x   1 root root    420 Mar 17 15:36 ..
-rwxr-xr-x   1 root root      0 Mar 17 15:36 .dockerenv
drwxrwxr-x   1 abc  users    38 Mar 16 16:55 app
drwxr-xr-x   1 root root    934 Mar 14 06:31 bin
drwxr-xr-x   1 root root     20 Mar 17 15:36 combustion-release
drwxr-xr-x   1 root root   5046 Mar 14 06:31 command
drwxr-xr-x   1 abc  users    42 Mar 17 15:36 config
drwxrwxr-x   1 abc  users    46 Mar 16 16:55 defaults
drwxr-xr-x   5 root root    340 Mar 17 18:47 dev
-rwxr--r--   1 root root  17702 Jan  1  1970 docker-mods
drwxrwxrwx   6 root root   4096 Mar 17 15:51 downloads
drwxrwxr-x   1 root root    766 Mar 17 18:47 etc
drwxr-xr-x   1 root root     20 Mar 17 15:36 flood-for-transmission
drwxr-xr-x   1 root root      0 Mar 14 06:31 home
-rwxr-xr-x   1 root root    907 Aug 29  2022 init
drwxr-xr-x   1 root root     20 Mar 17 15:36 kettu
drwxr-xr-x   1 root root    830 Mar 16 16:55 lib
drwxr-xr-x   1 root root     28 Mar 14 06:31 media
drwxr-xr-x   1 root root      0 Mar 14 06:31 mnt
drwxr-xr-x   1 root root      0 Mar 14 06:31 opt
drwxr-xr-x   1 root root     30 Mar 14 06:31 package
dr-xr-xr-x 434 root root      0 Mar 17 18:47 proc
drwx------   1 root root      0 Mar 14 06:31 root
drwxr-xr-x   1 root root    178 Mar 17 18:47 run
drwxr-xr-x   1 root root    984 Mar 14 06:31 sbin
drwxr-xr-x   1 root root      0 Mar 14 06:31 srv
dr-xr-xr-x  13 root root      0 Mar 17 18:47 sys
drwxrwxrwt   1 root root      0 Mar 16 16:55 tmp
drwxr-xr-x   1 root root     20 Mar 17 15:36 transmission-web-control
drwxr-xr-x   1 root root     20 Mar 17 15:36 transmissionic
drwxr-xr-x   1 root root     68 Mar 16 16:55 usr
drwxr-xr-x   1 root root     86 Mar 14 06:31 var
drwxr-xr-x   1 abc  users     0 Mar 17 15:36 watch
```

**Comment by lardbit** [comment]
Ugh, things seem ok.

Ok, let's make sure your user is what we think it should be:

    docker-compose exec transmission whoami

And lastly:

    docker-compose exec transmission ls -al /config

I'm running out of ideas.

**Comment by lardbit** [comment]
I did a fresh git clone of nefarious and it all came up fine.  Can you
elaborate on your host setup? Like, are you on Windows and using a VM for
docker?  Mac?

**Comment by ShrekRequiem** [comment]
`docker-compose exec transmission whoami` returns `root`
`sudo docker-compose exec transmission ls -al /config` returns 
```
ls: cannot access '/config/settings.json': Permission denied
total 0
drwxr-xr-x 1 abc  users  42 Mar 17 15:36 .
drwxr-xr-x 1 root root  420 Mar 17 15:36 ..
drwxr-xr-x 1 root root    8 Mar 17 15:36 crontabs
-????????? ? ?    ?       ?            ? settings.json
```
  as for my system its fedora, im trying to run nefarious from docker

**Comment by lardbit** [comment]
Well, see those question marks?  That usually means a permissions or
filesystem problem.  I'm guessing permissions.

My final thought would be that the directory you cloned nefarious into
doesn't have execute permissions so the transmission container can't list
its contents (where the settings.json file get mounted to).

**Comment by ShrekRequiem** [comment]
Well thank you so much anyway, you can mark this as closed and Ill comment if I find the issue so other people can see

**Comment by lardbit** [comment]
Closed.  Unknown installation issue.
