### ISSUE TITLE
Transmission Error In Docker

### ISSUE THREAD

**Issue by holty07** [lardbit/nefarious#248]
For some reason the Transmission container will not launch. When I try and launch it manually after everything else I get the error: `Error invoking remote method 'docker-start-container': Error: (HTTP code 500) server error - Ports are not available: exposing port TCP 0.0.0.0:51413 -> 0.0.0.0:0: listen tcp 0.0.0.0:51413: bind: An attempt was made to access a socket in a way forbidden by its access permissions.`
Let me know what I can share to assist troubleshoot as I have no idea how to look at this one.

**Comment by lardbit** [comment]
Are you on Windows by chance? This appears to indicate something is already
listening on port 51413 on your host system.

**Comment by holty07** [comment]
Yes, this is a windows machine running Docker desktop. I'll see what I can find about that port.

**Comment by holty07** [comment]
This has suddenly fixed itself now. This can be closed.
