### ISSUE TITLE
Error Log after fresh install

### ISSUE THREAD

**Issue by x-o-r-r-o** [lardbit/nefarious#249]
After installing and configuring jackett and transmission i went ahead to search but it came up with an error and than i went to discover and it popped up 2 error unexpected error. Than and went into docker logs and found out some how it is looking for redis and redis was not installed in this docker so i manually installed redis and restarted the container but still getting same error in logs.

`info:     192.168.100.16:50031 - "GET /api/genres/movie/?language=en%20HTTP/1.1%22%20500%20Internal%20Server%20ErrorINFO:%20%20%20%20%20192.168.100.16:50029%20-%20%22GET%20/api/discover/media/movie/?mediaType=movie&sort_by=popularity.desc&page=1&language=en%20HTTP/1.1%22%20500%20Internal%20Server%20ErrorERROR:django.request:Internal%20Server%20Error:%20/api/genres/tv/Traceback%20(most%20recent%20call%20last):%20%20File%20%22/env/lib/python3.9/site-packages/django_redis/cache.py%22,%20line%2032,%20in%20_decorator%20%20%20%20return%20method(self,%20*args,%20**kwargs)%20%20File%20%22/env/lib/python3.9/site-packages/django_redis/cache.py%22,%20line%2080,%20in%20get%20%20%20%20return%20self.client.get(key,%20default=default,%20version=version,%20%20File%20%22/env/lib/python3.9/site-packages/django_redis/client/default.py%22,%20line%20201,%20in%20get%20%20%20%20raise%20ConnectionInterrupted(connection=client,%20parent=e)django_redis.exceptions.ConnectionInterrupted:%20Redis%20ConnectionError:%20Error%2099%20connecting%20to%20localhost:6379.%20Cannot%20assign%20requested%20address.During%20handling%20of%20the%20above%20exception,%20another%20exception%20occurred:Traceback%20(most%20recent%20call%20last):%20%20File%20%22/env/lib/python3.9/site-packages/django/core/handlers/exception.py%22,%20line%2034,%20in%20inner%20%20%20%20response%20=%20get_response(request)%20%20File%20%22/env/lib/python3.9/site-packages/django/core/handlers/base.py%22,%20line%20115,%20in%20_get_response%20%20%20%20response%20=%20self.process_exception_by_middleware(e,%20request)%20%20File%20%22/env/lib/python3.9/site-packages/django/core/handlers/base.py%22,%20line%20113,%20in%20_get_response%20%20%20%20response%20=%20wrapped_callback(request,%20*callback_args,%20**callback_kwargs)%20%20File%20%22/env/lib/python3.9/site-packages/django/views/decorators/csrf.py%22,%20line%2054,%20in%20wrapped_view%20%20%20%20return%20view_func(*args,%20**kwargs)%20%20File%20%22/env/lib/python3.9/site-packages/django/views/generic/base.py%22,%20line%2071,%20in%20view%20%20%20%20return%20self.dispatch(request,%20*args,%20**kwargs)%20%20File%20%22/env/lib/python3.9/site-packages/django/utils/decorators.py%22,%20line%2043,%20in%20_wrapper%20%20%20%20return%20bound_method(*args,%20**kwargs)%20%20File%20%22/env/lib/python3.9/site-packages/django/utils/decorators.py%22,%20line%20130,%20in%20_wrapped_view%20%20%20%20response%20=%20view_func(request,%20*args,%20**kwargs)%20%20File%20%22/env/lib/python3.9/site-packages/rest_framework/views.py%22,%20line%20505,%20in%20dispatch%20%20%20%20response%20=%20self.handle_exception(exc)%20%20File%20%22/env/lib/python3.9/site-packages/rest_framework/views.py%22,%20line%20465,%20in%20handle_exception%20%20%20%20self.raise_uncaught_exception(exc)%20%20File%20%22/env/lib/python3.9/site-packages/rest_framework/views.py%22,%20line%20476,%20in%20raise_uncaught_exception%20%20%20%20raise%20exc%20%20File%20%22/env/lib/python3.9/site-packages/rest_framework/views.py%22,%20line%20502,%20in%20dispatch%20%20%20%20response%20=%20handler(request,%20*args,%20**kwargs)%20%20File%20%22/env/lib/python3.9/site-packages/django/utils/decorators.py%22,%20line%2043,%20in%20_wrapper%20%20%20%20return%20bound_method(*args,%20**kwargs)%20%20File%20%22/env/lib/python3.9/site-packages/django/utils/decorators.py%22,%20line%20122,%20in%20_wrapped_view%20%20%20%20result%20=%20middleware.process_request(request)%20%20File%20%22/env/lib/python3.9/site-packages/django/middleware/cache.py%22,%20line%20137,%20in%20process_request%20%20%20%20cache_key%20=%20get_cache_key(request,%20self.key_prefix,%20'GET',%20cache=self.cache)%20%20File%20%22/env/lib/python3.9/site-packages/django/utils/cache.py%22,%20line%20340,%20in%20get_cache_key%20%20%20%20headerlist%20=%20cache.get(cache_key)%20%20File%20%22/env/lib/python3.9/site-packages/django_redis/cache.py%22,%20line%2039,%20in%20_decorator%20%20%20%20raise%20e.parent%20%20File%20%22/env/lib/python3.9/site-packages/django_redis/client/default.py%22,%20line%20199,%20in%20get%20%20%20%20value%20=%20client.get(key)%20%20File%20%22/env/lib/python3.9/site-packages/redis/client.py%22,%20line%201332,%20in%20get%20%20%20%20return%20self.execute_command('GET',%20name)%20%20File%20%22/env/lib/python3.9/site-packages/redis/client.py%22,%20line%20836,%20in%20execute_command%20%20%20%20conn%20=%20self.connection%20or%20pool.get_connection(command_name,%20**options)%20%20File%20%22/env/lib/python3.9/site-packages/redis/connection.py%22,%20line%201073,%20in%20get_connection%20%20%20%20connection.connect()%20%20File%20%22/env/lib/python3.9/site-packages/redis/connection.py%22,%20line%20544,%20in%20connect%20%20%20%20raise%20ConnectionError(self._error_message(e))redis.exceptions.ConnectionError:%20Error%2099%20connecting%20to%20localhost:6379.%20Cannot%20assign%20requested%20address.`

**Comment by lardbit** [comment]
Let's back up a bit and try and find out why the version of Redis that's
included in this docker-compose.yaml wasn't working.

Can you do a full "docker-compose up --d --force-recreate" then try and
search for something in nefarious, and then show me the logs from
"docker-compose logs nefarious" and "docker-compose logs redis"

**Comment by lardbit** [comment]
Closed due to inactivity.
