### ISSUE TITLE
[Improvement] The title of the "Quality Profiles" in settings is ambiguous.

### ISSUE THREAD

**Issue by ouattararomuald** [lardbit/nefarious#264]
When I see "Quality Profiles" in settings, does it refer to the minimum quality profile that I select? If so, it should be clarified with another title, such as "Min Quality Profile."

**Comment by lardbit** [comment]
It's actually going to only find the exact quality match.  For example, if you have `720p` chosen, it will not download `1080p` files even if there aren't any `720p`.  

I'm open to making this more obvious with a better description on what it does.
