### ISSUE TITLE
Permissions Denied Error 

### ISSUE THREAD

**Issue by hav0ck** [lardbit/nefarious#284]
I'm running transmission 4.0.5 in docker and I am getting the following error when downloading a torrent

Error: Couldn't get '/downloads/incomplete/torrent.part': Permission denied (13)

My docker-compose has PUID and GUID set to 1000 and I'm using a cifs_mount to mount my downloads directory to where it needs to go.
I've verified that the destination download directory is owned by the proper user  with PUID and GUID of 1000.

When I console into the Transmission container the downloads folder is showing as being owned by root:root. In fact all folders except app, config, defaults, and watch are owned by root:root. The 4 folders not owned by root are owned by abc:users.

Here is my docker-compose file
version: "2.1"
services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/bert/transmission:/config
      - cifs_mount:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
volumes:
  cifs_mount:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.1.116/Home
      o: username=userID,password=passWD,file_mode=0777,dir_mode=0777

**Comment by lardbit** [comment]
I think mounting the samba share on the host via fstab ahead of time helps rule out any issues with docker attempting to manage the mount, but I know you're still having issues with that.  You don't have SeLinux enabled, do you?

Let's run some tests.

#### On the host

Write a file as user 1000:

    sudo -u \#1000 touch /Media/downloads/host_test

Did it work and is it owned by user 1000?

    ls -al /Media/downloads/host_test

#### Inside the docker container:

Get a shell inside the running container

    docker-compose exec transmission bash

Which user are we?

    id -u

Try writing a file:

    touch /downloads/container_test

Did it work and is it owned by user 1000?

    /downloads/container_test

**Comment by hav0ck** [comment]
So on the host I was able to create the host_test file

hmm the only way I can run any docker-compose command is to sudo it. I assumed that since I was specifying the GUID and PUID in the docker-compose.yaml file that container would run as the specified user. Do I have that wrong?
When I open a shell to the Transmission container I have to do so as sudo and when I do a ld -l to check the ownership downloads is owned by root:root.

**Comment by lardbit** [comment]
You can run docker containers as non-root if you follow the [post-install steps](https://github.com/lardbit/nefarious/blob/master/docs/DEPENDENCIES.md#post-install) but that certainly wouldn't explain why your container is seeing the permissions as `root` for that download directory.

Can you try running docker as a regular user (1000) and run the **Inside the docker container** steps again?

**Comment by hav0ck** [comment]
@lardbit I did a bit of digging and I found that I had used snap to install docker. I'm guessing that I check Docker off during the install as I've never used snap to install anything.
I removed the snap installed docker. installed the latest docker.io with APT.
I did a docker compose up for transmission and now everything is working properly

**Comment by lardbit** [comment]
Oh, excellent. That's a nice and simple ending to a problem. :fireworks:
