### ISSUE TITLE
feat: Add dependabot configuration for github action updates

### ISSUE THREAD

**Issue by disaac** [lardbit/nefarious#298]
* Currently, many of the GitHub actions are using older releases that are utilizing now deprecated methods. 
* Add a [dependabot.yml](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot) configuration to keep these actions up to date on a schedule automatically.

**Comment by disaac** [comment]
Fixed in [PR #299](https://github.com/lardbit/nefarious/pull/299)

**Comment by lardbit** [comment]
merged
