### ISSUE TITLE
Feature Request/import issue

### ISSUE THREAD

**Issue by frostbyte71901** [lardbit/nefarious#304]
I have alot of data that I have over time have added to my library manually, when I try to import my tv library or my movie library, it seems to just add some of them. it would be nice to have a way to tie it into en existing library from either jellyfin or plex. if there exists a way would you please advise on how to do so

**Comment by lardbit** [comment]
I assume you're importing your existing TV and Movies library via the buttons on the nefarious Settings page?  If it's only adding some, I do know of one issue that could affect that.  Only one "import" process is allowed at a time for this, so you'd need to first import TV, wait a bit, then import Movies.  I need to fix this.

If you've tried that and it's still not adding everything, please send me the logs from `docker-compose logs celery` (or clicking the logs button in the Settings page) and maybe I'll realize what's happening.

**Comment by frostbyte71901** [comment]
here is the log from my latest attempt. I got this log from portainer
[_nefarious_celery_1_logs.txt](https://github.com/user-attachments/files/16465883/_nefarious_celery_1_logs.txt)

**Comment by lardbit** [comment]
Closed due to inactivity.
