### ISSUE TITLE
Podman support ? 

### ISSUE THREAD

**Issue by Crupuk** [lardbit/nefarious#31]
Hi, 

Do you have plan to switch to Podman ? 

In rehl8 and Fedora 31 podman is the new default system for running container :

https://www.redhat.com/en/blog/working-linux-containers-rhel-8-podman-image-builder-and-web-console

Thanks

**Comment by lardbit** [comment]
I don't have plans but am not opposed. I mainly like how Docker Compose handles all the container connectivity and volumes and such. I haven't messed with Podman but it looks like they have a compatible option.

Have you used it?

**Comment by Crupuk** [comment]
Hi, thanks for your reply.

Not really used it , just installed bitwarden_rs ( https://fedoramagazine.org/manage-your-passwords-with-bitwarden-and-podman/ ) .

**Comment by lardbit** [comment]
It looks like it lacks the network and volume features that nefarious relies on with docker.  That's the nice thing about the `docker-compose.yml` setup is that it connects all the services together in their own network and has persistent volumes so things aren't lost even if you tear down the containers.

https://www.reddit.com/r/docker/comments/dh0ayb/thoughts_on_docker_vs_podman/f3gzeq4/

I don't see a way to use podman at this point and still make it simple for novice users.
