### ISSUE TITLE
Change download language; approve that vpn is running

### ISSUE THREAD

**Issue by Gentle-byte** [lardbit/nefarious#310]
Hello, I have two requests. So the installation went smoothly.

Firstly, is there an option to change the download language? I looked for an option to select the language of the downloaded video but didn't find one.

Secondly, is it possible to see if the VPN service is running and encrypting torrent traffic? I have "transmission" as the jackett host and it works so far. I just want to know if I'm really safe on the road. I´m using NordVPN.
Thanks in advance for answers

**Comment by lardbit** [comment]
> Firstly, is there an option to change the download language? I looked for an option to select the language of the downloaded video but didn't find one.

Are you asking if it's possible to choose the "dubbed" language or subtitles of the video?  

> Secondly, is it possible to see if the VPN service is running and encrypting torrent traffic? I have "transmission" as the jackett host and it works so far. I just want to know if I'm really safe on the road. I´m using NordVPN.

You can see the ip address of transmission with

    docker-compose exec transmission curl ifconfig.co

And you should notice it's different from your WAN ip

**Comment by Gentle-byte** [comment]
Okay, looks like my VPN works great. Well, with "changing language" I mean the "dubbed" language. Thanks for your answer

**Comment by lardbit** [comment]
Great for the vpn working as expected.  As for specifying a "dubbed" language, unfortunately nefarious doesn't have that feature yet.
