### ISSUE TITLE
Runs on port 80 by default?

### ISSUE THREAD

**Issue by thomashoeky** [lardbit/nefarious#36]
When starting the docker nefarious tries to start on port 80 instead of 8000, which can not be changed (on a Synology NAS)

//edit
Okay so apparently it tries to bind on port 80 and this is not allowed by the Synology Docker because it's already in use on the NAS itself, is there any way to change this port?

**Comment by lardbit** [comment]
Nefarious binds on port 8000 and forwards, internally to the docker container, to port 80. There shouldn't be any restriction on your NAS. I would verify nothing else is already open on port 8000.  You can edit the docker-compose.yml file to change the port if so
