### ISSUE TITLE
Https detection for wss websocket doesn't work right

### ISSUE THREAD

**Issue by l1pz** [lardbit/nefarious#41]
Hi!
I tried to setup nefarious with https for the last few hours, and I couldn't get the websocket work, with https. Then I looked at the code and saw that you use `${windowLocation.protocol === 'https' ? 'wss' : 'ws'}:` to determine _wss_ or _ws_. However _window.location.protocol_ returns "https:" with a colon, not simply "https", so it will always try to connect as ws, not wss.

**Comment by lardbit** [comment]
Good catch! Definitely a bug. You can probably guess I didn't test it on https.  Integrating https in nefarious by default is something I plan on doing.

In the meantime I'll fix up this bug you found.

**Comment by lardbit** [comment]
https://github.com/lardbit/nefarious/commit/056c037f6e00e40e9e4737b95a5d6bc457650d3f should address this issue.  Let me know, thanks.
