### ISSUE TITLE
Time to upgrade node js dependencies ?

### ISSUE THREAD

**Issue by ddonindia** [lardbit/nefarious#47]
I was trying nefarious today while running npm install I see following 

> **found 1310 vulnerabilities (937 low, 13 moderate, 358 high, 2 critical)**
>   run `npm audit fix` to fix them, or `npm audit` for details

Any plans to upgrade these ?

**Comment by lardbit** [comment]
Yes, thanks for pointing that out.  There's those npm ones and some python dependencies that need security updates I haven't gotten around to applying.  I did a quick `npm audit fix` and it fixed all but 19 *high* issues.  I didn't test the functionality yet, though.

I'll keep this open until then.

**Comment by lardbit** [comment]
I updated all the node dependencies in #71 .

`npm audit` now displays:

    found 0 vulnerabilities
