### ISSUE TITLE
[Feature] Ability to configure PUID and/or PGID

### ISSUE THREAD

**Issue by dfourn** [lardbit/nefarious#53]
It might already be a thing, I haven't checked yet. It would be useful for keeping the files created owned by the correct user. This feature is available in this image: https://hub.docker.com/r/linuxserver/transmission/

**Comment by lardbit** [comment]
Yeah you can do this with the supplied transmission image from *linuxserver*.  The full details are in the link you included, but here is the snippet of what you'd add to the transmission section in the `docker-compose.yml` file.

```
    environment:
      - PUID=1000
      - PGID=1000
```

Where you'd replace `1000` with whatever user/group id you want.

After adding this, just do a `docker-compose up -d` and it'll apply the changes.
