### ISSUE TITLE
problem installing nefarious

### ISSUE THREAD

**Issue by luisandre-debug** [lardbit/nefarious#56]
is this system made only for 64bit architecture? because I had this problem when trying to install nefarious:

> docker-compose up -d 
> Pulling jackett (linuxserver/jackett:)...
> latest: Pulling from linuxserver/jackett
> ERROR: no matching manifest for linux/386 in the manifest list entries

**Comment by lardbit** [comment]
The default settings are for x86 but there's also the https://github.com/lardbit/nefarious/blob/master/docker-compose.arm.yml which is for ARM architectures (raspberry pi, odroid etc).  See https://github.com/lardbit/nefarious/blob/master/ARM.md.

What architecture are you on?

**Comment by luisandre-debug** [comment]
> As configurações padrão são para x86, mas há também o [https://github.com/lardbit/nefarious/blob/master/docker-compose.arm.yml,](https://github.com/lardbit/nefarious/blob/master/docker-compose.arm.yml) que é para arquiteturas ARM (raspberry pi, odroid etc.). Consulte https://github.com/lardbit/nefarious/blob/master/ARM.md .
> 
> Em qual arquitetura você está?

my architecture is i686 32bits, i installed the docker using python's "pip install docker-compose" command, I don't know if it interferes with anything in the operation of nefarious

**Comment by lardbit** [comment]
nefarious should work fine with x86 / i686 architectures but it looks like the error you received is for i386:

    ERROR: no matching manifest for linux/386

I haven't tested it on 32 bit so maybe that is indeed an issue.  I will have to test it.

**Comment by luisandre-debug** [comment]
I ran the other command for installation

> docker-compose -f docker-compose.arm.yml up -d

now gave this error

> Creating nefarious_transmission_1 ... error
> WARNING: Host is already in use by another container
> Creating nefarious_jackett_1      ... error
> 
> ERROR: for nefarious_transmission_1  Cannot start service transmission: driver failed programming external connectivity on endpoint nefarious_transmission_1 (24c6f221d096a67310aeac443501b1081a528be109967691251bc9fbf793dd28): Error starting userland proxy: listen tcp 0.0.0.0:9091: bind: address already in use
> 
> Creating nefarious_watchtower_1   ... done
> Creating nefarious_redis_1        ... done
> Creating nefarious_celery_1       ... done
> 
> ERROR: for transmission  Cannot start service transmission: driver failed programming external connectivity on endpoint nefarious_transmission_1 (24c6f221d096a67310aeac443501b1081a528be109967691251bc9fbf793dd28): Error starting userland proxy: listen tcp 0.0.0.0:9091: bind: address already in use
> 
> ERROR: for jackett  Cannot start service jackett: driver failed programming external connectivity on endpoint nefarious_jackett_1 (aa5153f479c1ce8d21839dc369dd95f98f703f31141bb684206ef5cff997bfd0): Error starting userland proxy: listen tcp 0.0.0.0:9117: bind: address already in use
> ERROR: Encountered errors while bringing up the project.


i use radarr and sonarr so i never used docker, i installed it just to test this service, so i don't understand much.

my transmission I switched to port 9092 because the default is not working
and my jackett is running normal on port 9117

**Comment by lardbit** [comment]
Yes it looks like you're already running transmission & jackett so you'll have to either stop those instances first or just run nefarious without those two instances.

If you want to keep your existing transmission and jackett, then just run everything else with:

    docker-compose up -d nefarious celery redis watchtower

or, if you're using an ARM architecture:

    docker-compose -f docker-compose.arm.yml up -d nefarious celery redis watchtower

Then, when configuring nefarious, make sure to specify the IP addresses of transmission and jackett, something like:

![image](https://user-images.githubusercontent.com/45122868/84603362-824fae00-ae53-11ea-879f-208b9c2a625e.png)

**Comment by luisandre-debug** [comment]
I stopped the transmission and the jackett and executed the command

> docker-compose -f docker-compose.arm.yml up -d

now it appeared in the terminal

> nefarious_redis_1 is up-to-date
> Starting nefarious_jackett_1 ... 
> nefarious_watchtower_1 is up-to-date
> Starting nefarious_jackett_1      ... done
> Starting nefarious_transmission_1 ... done
> Creating nefarious_nefarious_1    ... done

what can be wrong? I ran the other command you said:

> docker-compose -f docker-compose.arm.yml up -d nefarious celery redis watchtower

> nefarious_redis_1 is up-to-date
> nefarious_jackett_1 is up-to-date
> nefarious_watchtower_1 is up-to-date
> nefarious_celery_1 is up-to-date
> nefarious_nefarious_1 is up-to-date

**Comment by lardbit** [comment]
That output looks correct and you should now be able to access nefarious
at: http://localhost:8000

**Comment by luisandre-debug** [comment]
after that i tried to start in the browser putting:
localhost: 8000
or 192.168.x.x: 8000 (my ip)
but it gives no sign.
like i said i'm a layman in docker and docker-compose.
after installing the docker do I have to do any configuration? install any dependencies or edit any files?
I thank you for your attention and excuse the silly questions

**Comment by lardbit** [comment]
Are you using the `docker-compose.yml` version for x86 or the `docker-compose.arm.yml` for ARM architecture?

Can you paste the output of:

    docker-compose ps

or

    docker-compose -f docker-compose.arm.yml ps

depending on which you're using?

**Comment by luisandre-debug** [comment]
> docker-compose -f docker-compose.arm.yml ps


              Name                        Command                 State                      Ports         
-----------------------------------------------------------------------------------------------
nefarious_celery_1         /env/bin/celery -A nefario ...         Restarting                         
nefarious_jackett_1        /init                                               Exit 128                           
nefarious_redis_1          docker-entrypoint.sh redis ...        Up                    0.0.0.0:6379->6379/tcp
nefarious_transmission_1   /init                                           Exit 128                           
nefarious_watchtower_1     /watchtower --label-enable ...   Restarting

**Comment by luisandre-debug** [comment]
I stopped the jackett and transmission
and then I ran the command to turn off the compose and then I gave up

> docker-compose -f docker-compose.arm.yml ps

          Name                        Command                 State              Ports         
-----------------------------------------------------------------------------------------------
nefarious_celery_1         /env/bin/celery -A nefario ...   Up           80/tcp                
nefarious_jackett_1        /init                            Up           0.0.0.0:9117->9117/tcp
nefarious_nefarious_1      /app/docker-entrypoint.sh        Up           0.0.0.0:8000->80/tcp  
nefarious_redis_1          docker-entrypoint.sh redis ...   Up           0.0.0.0:6379->6379/tcp
nefarious_transmission_1   /init                            Exit 1                             
nefarious_watchtower_1     /watchtower --label-enable ...   Restarting

**Comment by lardbit** [comment]
It says nefarious is running on port 8000 so it should be good to go.

Click [http://0.0.0.0:8000](http://0.0.0.0:8000).  This also assumes you're running nefarious on the same machine as you're testing.

**Comment by luisandre-debug** [comment]
> docker-compose -f docker-compose.arm.yml down

Stopping nefarious_nefarious_1  ... done
Stopping nefarious_celery_1     ... done
Stopping nefarious_redis_1      ... done
Stopping nefarious_jackett_1    ... done
Stopping nefarious_watchtower_1 ... done
Removing nefarious_nefarious_1    ... done
Removing nefarious_celery_1       ... done
Removing nefarious_transmission_1 ... done
Removing nefarious_redis_1        ... done
Removing nefarious_jackett_1      ... done
Removing nefarious_watchtower_1   ... done
Removing network nefarious_default


> docker-compose -f docker-compose.arm.yml up -d

Creating network "nefarious_default" with the default driver
Creating nefarious_redis_1        ... done
Creating nefarious_transmission_1 ... done
Creating nefarious_jackett_1      ... done
Creating nefarious_watchtower_1   ... done
Creating nefarious_celery_1       ... done
Creating nefarious_nefarious_1    ... done


> docker-compose -f docker-compose.arm.yml ps

          Name                        Command                 State             Ports        
---------------------------------------------------------------------------------------------
nefarious_celery_1            /env/bin/celery -A nefario ...        Up                  80/tcp              
nefarious_jackett_1            /init                                              Restarting                       
nefarious_nefarious_1        /app/docker-entrypoint.sh           Up                    0.0.0.0:8000->80/tcp
nefarious_redis_1               docker-entrypoint.sh redis ...      Restarting                       
nefarious_transmission_1   /init                                             Exit 1                           
nefarious_watchtower_1     /watchtower --label-enable ...     Up        


     

> docker-compose -f docker-compose.arm.yml ps

          Name                        Command                 State      Ports
------------------------------------------------------------------------------
nefarious_celery_1         /env/bin/celery -A nefario ...   Restarting        
nefarious_jackett_1        /init                            Restarting        
nefarious_nefarious_1      /app/docker-entrypoint.sh        Restarting        
nefarious_redis_1          docker-entrypoint.sh redis ...   Restarting        
nefarious_transmission_1   /init                            Exit 1            
nefarious_watchtower_1     /watchtower --label-enable ...   Restarting

**Comment by lardbit** [comment]
So now things look like they are restarting...

What does this return:

    uname -a

And

    docker-compose -f docker-compose.arm.yml logs nefarious

**Comment by luisandre-debug** [comment]
> uname -a

Linux andre-AOD270 5.3.0-59-generic #53~18.04.1-Ubuntu SMP Thu Jun 4 14:55:07 UTC 2020 i686 i686 i686 GNU/Linux


> docker-compose -f docker-compose.arm.yml logs nefarious

Attaching to nefarious_nefarious_1
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"
nefarious_1     | standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by lardbit** [comment]
Ok, so you shouldn't be using the docker-compose.arm.yml because you have
an i686 cpu (standard desktop cpu).

Please try the same commands without specifying that file and let me know.

Like

docker-compose up -d
docker-compose ps

**Comment by lardbit** [comment]
I just tested this on a fresh copy of nefarious on my i686 machine and it worked all right.

**Comment by luisandre-debug** [comment]
when I run this command
docker-compose up -d
it gives the error it gave at the beginning of the problem request on the page. you even said "nefarious it should work well with x86 / i686 architectures, but it looks like the error you received is for i386:"
but my computer is i686 and it seems to be giving error for this command.

I'm getting sad because I don't think it works on my system. I wanted to test the nefarious because the sonarr and radarr do not suit me well in some functions :(


> docker-compose up -d

Creating network "nefarious_default" with the default driver
Pulling jackett (linuxserver/jackett:)...
latest: Pulling from linuxserver/jackett
ERROR: no matching manifest for linux/386 in the manifest list entries

**Comment by lardbit** [comment]
I think you're right.  Maybe nefarious and the other images don't support 32-bit architecture :(

I'll have to test this out when I get some time.

Thanks for the feedback.

**Comment by luisandre-debug** [comment]
anyway, thanks for your attention, I will be following the project, who knows in the future I may be able to install it.

**Comment by lardbit** [comment]
nefarious does not have to run with docker.  You could always install it manually.  See https://github.com/lardbit/nefarious/blob/master/docs/DEVELOPMENT.md.

It's a bit technical so it might not be the best solution but wanted to give you the option.
