### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DillFrescott** [lardbit/nefarious#60]
Where is the media stored?

**Comment by DillFrescott** [comment]
Also one more question. How do I un-blacklist a result?

**Comment by lardbit** [comment]
Media is stored in whatever you set as `HOST_DOWNLOAD_PATH` in the `docker-compose.yml` file. It's default is `/tmp`.

You can clear blacklisted torrents by logging in to the admin here:
http://localhost:8000/admin/nefarious/torrentblacklist/

**Comment by DillFrescott** [comment]
Thank you so much!

**Comment by lardbit** [comment]
I should mention that `HOST_DOWNLOAD_PATH` is actually defined in the optional `.env` file.  See https://github.com/lardbit/nefarious#setup for details.

**Comment by DillFrescott** [comment]
Noted. Thanks
