### ISSUE TITLE
Tweak max size of torrents

### ISSUE THREAD

**Issue by DillFrescott** [lardbit/nefarious#61]
Is there a way to just tweak the maximum size of the torrents it finds? Its finding 20-30 GB complete seasons and i want to push it down a bit to about 10-15 GB.

**Comment by lardbit** [comment]
You have a couple options:

- Go to the *Settings* page and change the TV quality profile to a lower setting (i.e *sd*, *720p-1080p*)
- Manually search for the season so you can pick which one you want.  See [usage](https://github.com/lardbit/nefarious/blob/master/docs/USAGE.md)

**Comment by DillFrescott** [comment]
Ok. Thank you and sorry for all the questions. I appreciate all the work you do
