### ISSUE TITLE
Weird issue I ran into.

### ISSUE THREAD

**Issue by DillFrescott** [lardbit/nefarious#62]
It's not doing it anymore but I ran into a problem where transmission threw an error because the /downloads/ folder in the container was only 6.2 GB. So anything over that in size would fail to download.

**Comment by lardbit** [comment]
I'm not sure I can help with that one. Sounds like a host specific issue with space and/or mount problems.

**Comment by DillFrescott** [comment]
Ok no problem. Just thought I'd let you know.
