### ISSUE TITLE
[Feature] Add support to Usenet

### ISSUE THREAD

**Issue by lardissone** [lardbit/nefarious#68]
I would like to replace Radarr and Sonarr with Nefarious but I'm using them with Usenet (the only reason why I use both of them).

Are there any plans to add Usenet support in the future?

**Comment by lardbit** [comment]
I don't currently have plans to add Usenet.  My goal for nefarious was a project that anyone could use without the need for paid services.  I'm not opposed to including Usenet, but it's just not a priority because i don't personally use Usenet.  I've heard great things about it, though.  I'd like to try it one day.

**Comment by lardbit** [comment]
If anyone wants to give me access to a usenet provider I could probably add that feature in.

**Comment by FSCorrupt** [comment]
> If anyone wants to give me access to a usenet provider I could probably add that feature in.

i have some invites left, so i could Share one to you! would need an e-mail address!

**Comment by lardbit** [comment]
@FSCorrupt, thanks for offering! Before I take your offer, let me make sure I have the time to invest in this feature so I don't waste it.  Thanks again, I'll message you when I can commit some time.

**Comment by Clickbaitcake** [comment]
> I don't currently have plans to add Usenet. My goal for nefarious was a project that anyone could use without the need for paid services. I'm not opposed to including Usenet, but it's just not a priority because i don't personally use Usenet. I've heard great things about it, though. I'd like to try it one day.

I am a fan of keeping the project simple in the name of preventing feature sprawl and therefore harder to support and deploy. Moving into usenet adds complexity which I don't feel is needed. Would there be much to do as far as code is concerned?

**Comment by lardbit** [comment]
Yeah, I think it would be a decent lift, effort wise.  I didn't architect it in mind with having multiple download protocols so there'd be quite a lot of refactoring.
