### ISSUE TITLE
Layout trailers better

### ISSUE THREAD

**Issue by lardbit** [lardbit/nefarious#7]
I added trailer links to movies recently but didn't like how I added the actual links to the page.  It doesn't look great.

Do you have any better ideas? Buttons or something?

Something to note, though, there are an unknown amount of trailers returned from tmdb.org so, if space is an issue, we should just limit the maximum to like 5 or something.

The movie component: 
https://github.com/lardbit/nefarious/blob/master/src/frontend/src/app/media/media-movie.component.ts
https://github.com/lardbit/nefarious/blob/master/src/frontend/src/app/media/media-movie.component.html

Remember to run `npm --prefix src/frontend run watch` while you're developing so it'll constantly rebuild the app.  `run build` just does it once.

![image](https://user-images.githubusercontent.com/45122868/60544639-ceefb700-9cde-11e9-8ea4-c47d648759b1.png)

**Comment by toddbrady** [comment]
I would re-arrange the layout slightly. Put the hero image and details up
front, and instead of links to trailer, do thumbnails with a play icon on
them? When you click the links now, what happens? Maybe open the trailer in
a modal if it doesn't do it now.

Watch task, no problem...thats par for the course.

**Comment by lardbit** [comment]
I like the layout suggestion and modal idea. Do you think modal videos work well on mobile? The current links simply open into a new window, which, when on mobile devices will automatically open YouTube if it's installed. That's the only immediate advantage I can think of

**Comment by toddbrady** [comment]
I'll demo something up.
Bootstrap modals here:
https://getbootstrap.com/docs/4.3/components/modal/

**Comment by lardbit** [comment]
Cool.  They mention some issues with modals on mobile, but they may not be big issues.

https://getbootstrap.com/docs/4.3/getting-started/browsers-devices/#modals-and-dropdowns-on-mobile

**Comment by lardbit** [comment]
Oh, and nefarious is using the angular + bootstrap library https://ng-bootstrap.github.io/ which includes modals.  Check that out.  It has modals and examples too.

**Comment by toddbrady** [comment]
So I have the site running, but still need a few things to get it working
all the way.
What's the reco for Jacket, Redis, & Transmission?

Also, when I tried to run celery I got the following (I guess I need redis
first?):

odds-MacBook-Pro:nefarious toddbrady$ cd src/

Todds-MacBook-Pro:src toddbrady$ celery -A nefarious worker --loglevel=INFO



 -------------- celery@Todds-MacBook-Pro.local v4.2.1 (windowlicker)

---- **** -----

--- * ***  * -- Darwin-18.0.0-x86_64-i386-64bit 2019-07-03 02:19:23

-- * - **** ---

- ** ---------- [config]

- ** ---------- .> app:         nefarious:0x10b98dbe0

- ** ---------- .> transport:   redis://localhost:6379/0

- ** ---------- .> results:     disabled://

- *** --- * --- .> concurrency: 8 (prefork)

-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this
worker)

--- ***** -----

 -------------- [queues]

                .> celery           exchange=celery(direct) key=celery




[tasks]

  . nefarious.tasks.completed_media_task

  . nefarious.tasks.refresh_tmdb_configuration

  . nefarious.tasks.wanted_media_task

  . nefarious.tasks.wanted_tv_season_task

  . nefarious.tasks.watch_movie_task

  . nefarious.tasks.watch_tv_episode_task

  . nefarious.tasks.watch_tv_show_season_task


[2019-07-03 02:19:24,114: ERROR/MainProcess] consumer: Cannot connect to
redis://localhost:6379/0: Error 61 connecting to localhost:6379. Connection
refused..

Trying again in 2.00 seconds...


[2019-07-03 02:19:26,127: ERROR/MainProcess] consumer: Cannot connect to
redis://localhost:6379/0: Error 61 connecting to localhost:6379. Connection
refused..

Trying again in 4.00 seconds...


[2019-07-03 02:19:30,148: ERROR/MainProcess] consumer: Cannot connect to
redis://localhost:6379/0: Error 61 connecting to localhost:6379. Connection
refused..

Trying again in 6.00 seconds...


[2019-07-03 02:19:36,164: ERROR/MainProcess] consumer: Cannot connect to
redis://localhost:6379/0: Error 61 connecting to localhost:6379. Connection
refused..

Trying again in 8.00 seconds...


^Z

[1]+  Stopped                 celery -A nefarious worker --loglevel=INFO

Todds-MacBook-Pro:src toddbrady$

**Comment by toddbrady** [comment]
also, the watch task seemed to break the server:

^C(nefarious) Todds-MacBook-Pro:nefarious toddbrady$ DEBUG=1 python
src/manage.py runserver 8000

Performing system checks...


System check identified no issues (0 silenced).

July 03, 2019 - 02:32:33

Django version 2.1.5, using settings 'nefarious.settings'

Starting development server at http://127.0.0.1:8000/

Quit the server with CONTROL-C.

[03/Jul/2019 02:32:36] "GET /static/index.html HTTP/1.1" 404 1654

**Comment by lardbit** [comment]
> So I have the site running, but still need a few things to get it working all the way. What's the reco for Jacket, Redis, & Transmission? Also, when I tried to run celery I got the following (I guess I need redis first?)

Yeah, celery is complaining about not being able to connect to Redis.

For running jackett, transmission & redis, you'll have to download and run them individually.  Transmission and Jackett have macos specific downloads, where redis looks like the recommended way is by using Homebrew.

However, I recommend running them via docker so you don't have to download & run each one separately.

If you have docker & docker-compose installed, you can just do:
    
    docker-compose up -d transmission jackett redis


**Side Note** I need to update the instructions, but run celery with `DEBUG=1` in front.  This sets a flag where nothing is actually downloaded in transmission.  Things get added to transmission but are paused.  This is useful if you're not behind a VPN while developing.

    cd src
    DEBUG=1 celery -A nefarious worker --loglevel=INFO

**Comment by lardbit** [comment]
> also, the watch task seemed to break the server

Yeah, you're seeing an error because celery isn't running (because redis wasn't running).

When you click the Watch button it tries adding a task to celery (and into redis).
