### ISSUE TITLE
Accent doesn't match

### ISSUE THREAD

**Issue by JorTurFer** [lardbit/nefarious#75]
I have an issue related with the accents in Spanish. I am trying to download a TV show named 'Érase una vez'.
When the celery container starts, it prints:
```bash
INFO  2020-12-24 17:58:10,288  processors 12  4159525392  Processing request to watch Érase una vez - S01E07
```
When jackett is queried, it returns :
![image](https://user-images.githubusercontent.com/36899226/103102129-e3ceb180-461a-11eb-88f6-6a3c3c1d1ba0.png)

But when celery process the result, it says this:

```bash
INFO  2020-12-24 17:57:59,498  processors 14  4159525392  Not matched: Erase Una Vez S01E07 SPANISH SDTV XviD
[2020-12-24 17:57:59,498: INFO/ForkPoolWorker-5] Not matched: Erase Una Vez S01E07 SPANISH SDTV XviD
```

My nefarious' config is this:
![image](https://user-images.githubusercontent.com/36899226/103102233-6b1c2500-461b-11eb-8477-d0d73d14735e.png)

I also tried using DEBUG loglevel in celery in order to get more info related with this but I haven't got any reason in logs. 
With this data, I suppose that the problem is related with the accents.

Sorry because I don't have knowledge in python to fix it or get more specify cause.
The tracker that I am using to resolve this TV show is DivxTotal (if you need to try)

EDIT: After download some episodes looking for them manually, I discover that the name after the torrent rename is `Once Upon a Time`. Is  this the name that uses to match the jackett response? I don't understand it because that jackett request is for the episode in Spanish, but the internal name is in English

Thanks for support

**Comment by lardbit** [comment]
Thanks for the detailed report.  I think nefarious is not handling accents correctly.  Nefarious is testing the accented name **Érase una vez** to jackett's result **Erase Una Vez** and not matching them.

That's something I can definitely try and address.  

However, I still can't determine how/why it's renaming it to the english translation *once upon a time*.  Are you saying that once nefarious downloads any episodes it renames the actual files to *Once upon a time*?

**Comment by lardbit** [comment]
Ok I think I [implemented[(https://github.com/lardbit/nefarious/commit/2f1bb03ed331f118f4e55bed9fd33d6444c07c52) a good enough solution.  I'm using the package https://github.com/avian2/unidecode which is a "good enough" ascii transliteration of unicode characters.

I tested your same show **Érase Una Vez** and nefarious downloaded the correct torrent and renamed it accurately:

    Valid Match: Erase Una Vez S01E01 SPANISH SDTV XviD with 1 Seeders
    ....
    Renaming torrent file from "Erase.Una.Vez.1x01.HDTV.XviD.[www.DivxTotaL.com].avi" to "Érase Una Vez - S01E01.avi"

Update your copy of nefarious and let me know how it goes.

**Comment by JorTurFer** [comment]
Thanks!!
I tried with the latest docker version and it works fine :) 
I was thinking about the english rename and I found that it happens when I add a torrent that I found manuallly using the "Manually Serach" tab. If nefarious found the torrent automaticaly there is not any problem.
With this fix, I will not need more manual search I think :)

**Comment by lardbit** [comment]
Great! Thanks for confirming it's resolved and helping with the international issues.
