### ISSUE TITLE
[Feature] Per-show Quality Profile override

### ISSUE THREAD

**Issue by scruloose** [lardbit/nefarious#77]
Loving Nefarious so far; thanks for this nifty project!

The Quality Profile setting is very handy, and I would suggest taking that feature one step farther. Some shows I don't care too much about the quality (eg talky dramas that don't rely much on visuals, or shows that I *may* get around to watching some day) so for those shows I would like to set a lower quality profile and save some disk space. But for the latest flashy sci-fi that I'm really actively watching, I want to get the highest quality my TV will support, of course.

For my purposes, it would be perfect to have a "Quality Profile for this show" option on the top-level series description page, right near the "Stop watching show" and "Watch all seasons" buttons. Presumably it would present the same listbox that's used in the settings page, with the current overall default pre-selected. (Or maybe just a ticky-box for "Specify Quality Profile for this show", unticked by default, and have the listbox only appear when you tick the box. I'm no expert in UI or web-app design. ☺)

**Comment by lardbit** [comment]
Yeah I definitely agree.  I think the reason I haven't implemented it yet for TV shows is because it was less clear to me how to implement it.  For example, adding it for movies was straight forward because you're only specifying it for a single file.  But, for TV, you could ask the user what quality they want for the entire show or for specific episodes.  In a perfect situation it'd be nice to have the granularity to specify for each episode.  

I'll give this some thought, but the quality feature should definitely work for TV too.

**Comment by scruloose** [comment]
Well, personally I don't really see a use-case for the per-episode level of granularity, and I would prefer to see per-series quality setting implemented sooner vs per-episode granularity but wait longer for it… if it were my choice. ;-)

That said, I assume it wouldn't be hard to make the back-end support a hierarchy of per-episode → per-season → per-series → overall default; in which the most granular one that's actually set takes precedence. That should pave the way for adding per-series control to the interface in the near-term while leaving the door open to more granularity later, if I understand things correctly.

In terms of UI implementation for more granular control, I wonder whether another column of ticky-boxes similar to the current setup for "watch selected episodes" would make sense. Like, have one column of ticky-boxes for "watch" and a second column (greyed out for episodes that aren't selected to watch, I would assume) for "specify quality profile". Then the user could tick one or more episodes and override their quality profile with a listbox down near the "watch selected episodes" button.

I guess you'd want to squeeze the current effective quality profile for each series, season, and/or episode into the display too… Maybe little colour-coded badges for SD, HD, 720, 1080, 4k, etc would  help to display that in an easily-readable but compact way.

I hope there's something helpful in those rough brainstorming ideas!

**Comment by lardbit** [comment]
This is all great feedback, I appreciate it.  The next big thing I'm going to refactor is the TV page.  I've never liked the layout/interface that I initially created.  When I do tackle it, I'll definitely implement the quality setting.

**Comment by scruloose** [comment]
Oh, and I have a subtle UI suggestion!

If you go with the little colour-coded badges idea, it might be helpful to have two versions of each badge: one with the colour at full saturation, which indicates that the profile has been explicitly set *at this level of granularity*, and a "faded" lower-saturation version, which indicates that the profile has been inherited from a more general scope, *not* explicitly set at this scope. The Firefox plugin uMatrix uses that approach. Every cell in the matrix is colour-coded: rich red for explicit `block`, pale red for `block` inherited from a more general rule, rich green for explicit `allow`, and pale green for `allow` inherited from a more general rule. I found it kind of amazing how helpful it is having that extra little piece of information included — and elegantly, it doesn't take up *any* more UI space.

Maybe the little colour-coded badge could actually be a button, which pops up the "select quality profile" listbox when clicked. (To make it really slick, have the list show the colour-coded badges rather than plain text; all rich colour except the "inherit default" option could show up in the faded-out colour of the current effective profile of the parent scope.) That would be a little tidier and more compact than a column of ticky-boxes plus a quality badge for each episode… and hopefully just as intuitive.

Still just brainstorming… maybe it'll come in handy, depending on the implementation details.

**Comment by JorTurFer** [comment]
any update?

**Comment by lardbit** [comment]
No, but I do think this is a higher priority feature request.  I just haven't had the chance to address it.

**Comment by JorTurFer** [comment]
Don't worry, it is a simple question
As I said several times, you are doing an amazing job with this. 
I ❤️ nefarious

**Comment by lardbit** [comment]
@JorTurFer, @scruloose ,  I added this feature.  It's currently on a separate branch until I run it locally for a few days to make sure it works as expected.  I'll keep you posted.

See #139.

**Comment by JorTurFer** [comment]
Nice!!! I will stay tuned :)
It looks good:)

**Comment by lardbit** [comment]
And there you have it, only 9 months later :)
