### ISSUE TITLE
UID and GID values don't seem to be applied in transmission-vpn setup

### ISSUE THREAD

**Issue by scruloose** [lardbit/nefarious#78]
I'm an experienced Linux user but a complete noob when it comes to Docker, so apologies if I'm missing something obvious…

In my `.env` file, I have set the `HOST_DOWNLOAD_UID` and `HOST_DOWNLOAD_GID` values to correspond to the user that actually invokes docker-compose.  I assume this is supposed to prevent the strange and alarming outcome of files created by Nefarious in the "Host Download Path" being owned by root on the host system, yes?

Those files are, however, all created with owner and group `root` in my case. I'm using the transmission-vpn setup (which, in general, seems to be working fine including port forwarding). From a quick look through the config files in `~/nefarious`, I see that those two environment variables are referenced in `docker-compose.yml`, section `transmission`:

      environment:
          - PUID=${HOST_DOWNLOAD_UID:-1000}
          - PGID=${HOST_DOWNLOAD_GID:-1000}

In `docker-compose.transmission-vpn.yml`, however, they seem to be missing. (Or, if the yml files cascade the way they look like they do, maybe those two settings should be moved to docker-compose.base.yml and inherited by the with/without vpn variations rather than duplicated, but I'm pretty much guessing in the dark at this point.)

Also, I hope this isn't a rude question, but... is Nefarious itself running as root in the container, or is it just that root is needed for setting up the, um, mounts? volumes? I ask because decades of Linux experience makes me very uncomfortable with anything running as root that doesn't **absolutely need** root privileges, and container-escape vulnerabilities do turn up occasionally. I'm not too proud to admit that I pretty much freaked out when I saw that this containerized app was creating files and directories **as root on the host system**.    ☺

**Comment by lardbit** [comment]
Hey @scruloose,

You're right about both things: the `docker-compose.transmission-vpn.yml` is missing the environment variables to configure the user id and group id that the container should run as.  

In the short term, it should include the same section like:

    environment:
      - PUID=${HOST_DOWNLOAD_UID:-1000}
      - PGID=${HOST_DOWNLOAD_GID:-1000}

However, in the long term, you're right that it could probably live in `docker-compose.base.yml` so it's not duplicated.  I'll make that change.

And for the 2nd thing, nefarious is indeed running as root inside the container.  I realize that's a security no-no but i just haven't tackled that part yet.  I haven't researched yet how to run docker containers as specific users.  I'm sure it wouldn't be too difficult to implement and I am definitely interested in doing it correctly.  

You're quickly becoming the best person for insight and feedback, I appreciate it.

**Comment by lardbit** [comment]
I may get to tackle some of these issues next week.  I'll have some downtime.

**Comment by scruloose** [comment]
Cool, I'll try adding those lines to `docker-compose.transmission-vpn.yml` for now.

> You're quickly becoming the best person for insight and feedback, I appreciate it.

Haha, thanks! I'm not much of a coder myself, but I am a bit of a security nerd and I seem to have a knack for weird edge-case configurations that break things in interesting ways. I hope you don't end up going "oh no what now" when you see my handle.  ☺

**Comment by lardbit** [comment]
I'm working on updating nefarious to run as a non-privileged user but am running into a problem.  It's currently configured to run on port `80` but only privileged users can run on that low of a port.  I can obviously update the `docker-compose.base.yml` to map to a different port, but then new docker images of nefarious would break people's installations until they manually updated their docker compose files.   nefarious auto-updates to the newest docker images so that would be a problem.

**Comment by scruloose** [comment]
Well, I have two thoughts:
* Nefarious is not a general-purpose web server, so grabbing port 80 might be... bad form. I suspect that's basically why Transmission and Jackett and other special-purpose webapps tend to use the nonstandard high-numbered ports they do. If you follow suit and use another unpopular/unused port number for Nefarious, that would leave a user the flexibility to run it alongside a web server hosting their website or whatever. Then visitors hitting the host system on port 80 would get the website, and the owner could access their Nefarious, Transmission, and Jackett instances as needed by specifying the port… without having to get into port-mappinng NAT setup or figuring out how to get nginx to handle Nefarious-in-a-Docker-container as a subdomain or whatnot.
* Now, while the project is very young and has only a small userbase of early adopters, it's easier to make incompatible changes than it will be later.  ;-)

That said, I'm fairly sure that letting a non-root process use a low-numbered port is possible and feasible.

On a normal non-containerized system, I would use a systemd 'system' `.socket` and `.service` unit pair to listen (as root) on port 80, do whatever privileged setup steps might be needed (in `ExecStartPre=`), then drop privileges by starting the Nefarious server process with `User=` and `Group=` explicitly set, similar to how, say, nginx runs as a dedicated user `nginx`, not as root, but still uses privileged low-numbered ports. (Side note: one neat thing about this setup is that nginx doesn't even have to be *running* to listen on that port. When somebody hits port 80, systemd will cache the incoming packets, start nginx, hand it the cached packets once it's up, then attach it to the real port and let it do its thing.)

I don't know Docker so I don't really have any insight to offer on the implementation details… I do know that it's geared toward "one process per container" so there's nothing like a full init system in there. However, I'd be pretty surprised if Docker doesn't provide an equivalent way to first grab the port as root and assign it to (or reserve it for, or whatever the exact terminology is) the Nefarious process, then launch the Nefarious process as its own dedicated user and hand it the already-established port binding. If all else fails, you could probably grab an "official" nginx container and see how they do it.

Ideally, I think you want to to use this approach even if you **do** go with a high-numbered port. Then any users who really want the old behaviour back can change the config to port 80 and things will still work as expected. I suspect you'll likely have to do something similar in terms of accessing filesystem paths on the host, too. (`mount`, traditionally, is a privileged operation.)

Good luck!

**Comment by lardbit** [comment]
Thanks for the detailed feedback!  You inspired me to delve into binding low ports as non-privileged users and I think I found a solution that solves the following goals:

- keep the nefarious *container* running on port `80` for backwards compatibility with existing users so nothing breaks
- run nefarious as non-root

I ended up going with [authbind](http://manpages.ubuntu.com/manpages/trusty/man1/authbind.1.html) which seems to do the trick.  You can see the implementation details in #80.

Your first bullet point makes sense, and I wish I had designed the compose stack to use nginx or caddy or something to give people more flexibility for a reverse proxy & ssl.  However, nefarious isn't technically binding to port `80` on the host.  It's actually binding to port `8000` and then docker is forwarding to the container's port `80`.

**Note**: I still need to test the transmission UID/GID environment changes I threw in last minute, but the non-root user and port binding worked well.

**Comment by lardbit** [comment]
I admit I'm probably clinging on too much to backward compatible changes for such a small user-base.  My hesitation only revolves around the auto-update feature that's baked in to the compose file, which would immediately break every user's app.

Eventually I'll just use a new docker image tag, like `v2` vs `latest` so any new big changes will be opt-in.

**Comment by scruloose** [comment]
Oh, right! I had forgotten that it's already using a high-numbered port on the host. If Docker handles the port-mapping NAT stuff painlessly, then I'd say that's a non-issue. Certainly nothing worth breaking the entire base install over. I *do* like ssl, though. If a future version had that capability, that would be pretty exciting. (Then I might actually forward a port on my router so I could access Nefarious from outside my home LAN!) I have a very basic nginx server set up with Let's Encrypt already, but I don't have the first clue how one might go about integrating a thing in a Docker container with that. I might look into it, but right now there are at least three projects that are more urgent and/or more interesting, so it's in the "maybe some day" stack…

I've never used `authbind`, but it does look like this is exactly what it's designed for.

And yes, if Docker gives you an easy way to do major new versions on an opt-in basis, that sounds like the way to handle any breaking changes.  What little I know about release management comes from the world of apt packages (which are alarmingly complicated, but do have decent support for managing config changes on upgrades.)

I look forward to trying out the new changes!

**Comment by lardbit** [comment]
If you already have nginx + lets encrypt, then you can setup a [reverse proxy in nginx](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/) to forward requests to nefarious.

Something like:

```
server {
    listen       443;
    server_name  nefarious.example.com;

    location / {
        proxy_pass http://127.0.0.1:8000;
    }
}
```


However, I've been using [Caddy](https://caddyserver.com/) recently because of it's simplicity and it comes baked in with Lets Encrypt.  I'm sure it doesn't offer as many features but it does a great job.

**Comment by scruloose** [comment]
Okay, I have to admit that does look pretty straightforward. Maybe I'll set that up sooner rather than later after all.

Caddy looks nice & slick too! If I didn't already have a setup I'm happy with, I'd probably give that a spin.

**Comment by lardbit** [comment]
Thanks again for the help.

**Comment by lardbit** [comment]
Reopening due to a breaking change noted in #81.  A root-owned file used by the task manager (celery) was unable to be written to since it's now running as a non-root user.  I reverted the changes and am thinking of a solution in the meantime.
