### ISSUE TITLE
[Bug] On nefarious container logs

### ISSUE THREAD

**Issue by plagioriginal** [lardbit/nefarious#86]
Hi, 
Having a problem with the arm setup, I think. There is an error when I do `docker-compose logs -f nefarious` and it prevents me from seeing the login page on nefarious.

Here are the logs 

![Screenshot_2021-02-01-21-47-14-512_com server auditor ssh client](https://user-images.githubusercontent.com/33816700/106522494-bd344e00-64d7-11eb-9807-b5152ae6ed6c.png)

Can someone help?

Thank you :)

**Comment by lardbit** [comment]
Hi @plagioriginal,

I pushed a change this week that runs nefarious as a regular user (vs root) and attempted to make it backwards compatible with existing users.  It seemed to work for me, but I it looks like I must have missed something.

Let me investigate a solution and get back to you.

**Comment by plagioriginal** [comment]
Thanks @lardbit :)
If you think it's better, I don't mind at all to rebuild it

**Comment by lardbit** [comment]
Hi @plagioriginal,

Would you mind running these commands and telling me their output?

    docker-compose exec nefarious ls -ald /nefarious-db
    docker-compose exec nefarious ls -al /nefarious-db

The second one should be like:

![image](https://user-images.githubusercontent.com/45122868/106616478-390fb400-6533-11eb-8fd3-f50c321966a4.png)

But I think yours will show that the files are owned by *root* which is a mistake.  

If this is true, then we have two options:

First stop everything:

    docker-compose -f docker-compose.arm.yml down

1)  Manually change permissions on the configuration directory so it can be owned by a regular user (**nonroot**) and you won't have to rebuild nefarious:

Get the docker volume name.  It should be **nefarious_nefarious-db** but run this to make sure:

    docker volume ls --format "{{.Name}}" --filter "name=nefarious-db"

Take that value and then run:

    docker volume inspect --format "{{.Mountpoint}}" nefarious_nefarious-db

That'll tell us where the config directory is stored on your host, which we'll just need to change the permissions with something like:

    sudo chown -R 10000:10000 /var/lib/docker/volumes/nefarious_nefarious-db/_data

Then just restart everything and you should be back to normal:

    docker-compose -f docker-compose.arm.yml up -d --force-recreate

2) This option will destroy the config directory (docker volume) and you'll have to setup nefarious again:

Get the docker volume name as in step 1, then run something like:

      docker volume rm nefarious_nefarious-db

Then restart everything:

    docker-compose -f docker-compose.arm.yml up -d --force-recreate

**Comment by plagioriginal** [comment]
Hi @lardbit 
Thank you, the first steps worked perfect :)
