### ISSUE TITLE
Install without using docker

### ISSUE THREAD

**Issue by AlienProber** [lardbit/nefarious#92]
I currently have Sonarr and Raddar install and love them. I want to set up similar on my roommates machine, but he needs something that's more like your offerings, everything in one. The issue is I do not want to use docker at all. Is there a way to install and get nefarious up and running without docker? Thanks

**Comment by lardbit** [comment]
You can certainly run nefarious without docker but you have to be very technically savvy.  See https://github.com/lardbit/nefarious/blob/master/docs/DEVELOPMENT.md.

If you're not that savvy, then docker is by far the easiest.
