### ISSUE TITLE
[Feature] Custom completed Movies & TV Shows directory

### ISSUE THREAD

**Issue by C-Fu** [lardbit/nefarious#93]
So far so good! Shouldn't have put off trying this out for so long lol

Anyway seems like there is no (easy? clear?) way to customize where the completed movies and tv shows go. Current setup via Xpenology:

$ nano .env
HOST_DOWNLOAD_PATH=/volume2/Downloads/

For movies: /volume2/Downloads/completed/movies
For tv shows: /volume2/Downloads/completed/tvshows

Actual/preferred media path:
/volume2/Media/Movies
/volume2/Media/TVShows

I've set it up this way so I can just rclone the /Media folder to my gdrive ever few hours or so.

I'm guessing currently I'd have to do a cron job of moving the subfolders in completed/movies and tvshows into /Media/Movies and /Media/TVShows. So it would be awesome if the .env file can set a custom folder for both media types. 

Plex integration (as in the auth or user accounts feature) would be great, but really not necessary.

10 stars!!

**Comment by lardbit** [comment]
Hmm, you're right.  There's no *clear* way to do this.  Here's how it's possible:

If you're **not** using the built-in vpn/transmission, then you'd update `transmission-settings.json` and update *download-dir* to not include a sub-path.  It's `/downloads/completed` by default but just update it to `/downloads` like:

```
{
    "download-dir": "/downloads",
}
```

Then everything will download to the root path of your host-mounted path `HOST_DOWNLOAD_PATH`.

And then do the same to `docker-compose.base.yml` for **celery-base** and strip off the `/downloads/completed` sub-path:
```
celery-base:
  environment:
    INTERNAL_DOWNLOAD_PATH: /downloads  # <-- this line
``` 

Then recreate transmission:

    docker-compose up -d --force-recreate transmission   


If you **are** using the vpn/transmission feature, then you can accomplish it via environment variables.  nefarious uses two different transmission images depending on needing a vpn or not, so they have different settings.

Edit `.env` and add something like:

```
TRANSMISSION_DOWNLOAD_DIR=/data
```


Then recreate transmission:

    docker-compose up -d --force-recreate transmission

**Comment by lardbit** [comment]
no response - closing
