### ISSUE TITLE
[Feature] Allow add headers in the webhook

### ISSUE THREAD

**Issue by JorTurFer** [lardbit/nefarious#95]
In the UI settings appears an option to execute webhook after a download is completed. This feature is amazing to synchronize the libraries of an external media server. The point here is that media servers like jellyfin expose an API with authentication and the authentication model uses a [specific header](https://api.jellyfin.org/).
If nefarious brings the possibility of add custom headers in the webhook executions will support to make direct calls to the Jellyfin API and trigger the synchronization when the movement after completion is done.

Thanks for you great job :)

**Comment by lardbit** [comment]
I like this idea.  I originally built the webhook to suit my needs for getting a push notification when something was downloaded, but this would make it more flexible.

**Comment by JorTurFer** [comment]
After depth in the jellyfin code,I found that the [ApiKey can be provided as a query string parameter](https://github.com/jellyfin/jellyfin/blob/c1bb29532fd4abb0245799df0cc6e9cd6d576568/Emby.Server.Implementations/HttpServer/Security/AuthorizationContext.cs#L89) (I think that this option is not documented). I close this issue because is not necessary :)

**Comment by lardbit** [comment]
Oh, well that's convenient
