### ISSUE TITLE
Possibility to select "HDR" as a quality option

### ISSUE THREAD

**Issue by jordyvandomselaar** [lardbit/nefarious#97]
Original discussion: [https://github.com/lardbit/nefarious/discussions/96](https://github.com/lardbit/nefarious/discussions/96)

It would be really cool if it was possible to select "HDR" as a quality preset. Right now it is possible to select `ultra-hd` which selects 4k content but it does not select 4k HDR content.

Because of this I have to use the manual search every time I'd like to get HDR content.

Thanks in advance!

**Comment by lardbit** [comment]
Thanks for creating this issue.  Can you tell me which specific tags you look for when trying to get "4k hdr"?  These quality labels aren't totally clear to me. Do you think "RAW HD" is synonymous with "4k HDR"?

**Comment by jordyvandomselaar** [comment]
As far as I can see it's usually in the name. HDR is not really a quality profile because any resolution can also have HDR. I think it's more of an additional setting on top of quality.

**Comment by lardbit** [comment]
That makes sense. I wonder if nefarious should include check boxes in
addition to quality profiles to further specify: HDR, RawHD etc since
they're not qualities themselves.

**Comment by jordyvandomselaar** [comment]
That would be awesome =)

**Comment by lardbit** [comment]
Alright, I'm sold on the idea.  I'll keep this issue open until I have some time to tackle it, but my current idea is to keep the existing profiles but then include checkboxes for "modifiers".  The radarr projects uses these but I don't really understand all of them and will at least include "HDR":

- REGIONAL
- SCREENER
- RAWHD
- BRDISK
- REMUX

**Comment by Clickbaitcake** [comment]
> Alright, I'm sold on the idea. I'll keep this issue open until I have some time to tackle it, but my current idea is to keep the existing profiles but then include checkboxes for "modifiers". The radarr projects uses these but I don't really understand all of them and will at least include "HDR":
> 
> * REGIONAL
> * SCREENER
> * RAWHD
> * BRDISK
> * REMUX

This Wiki explains them pretty well: https://en.wikipedia.org/wiki/Pirated_movie_release_types

**Comment by lardbit** [comment]
Thanks @Clickbaitcake, that's definitely helpful.  I plan on downloading sonarr at some point to mirror some of it's quality profile logic when I'm ready to tackle this.

**Comment by lee-b** [comment]
I think HDR is a value of a color-space property, in the same way that 1080 is a value of a vertical-resolution property.

So 1080p should inform the vertical-resolution and refresh-rate properties, and HDR should inform the colour-space property.

Then there is the bit-rate property.

None of these alone tell you the overall quality, but that could be calculated by combining the different properties.

**Comment by lardbit** [comment]
You can now apply "HDR" rules to quality profiles.  See https://github.com/lardbit/nefarious/pull/212
